## Ablation Study with LightGBM

**Cell 1: Imports**

In [16]:
import json
import time
from pathlib import Path

import numpy as np
import scipy.sparse as sp
import joblib
import lightgbm as lgb
from math import ceil

from lightgbm import LGBMClassifier

print("Imports loaded OK")

Imports loaded OK

**Cell 2: Check the folders to find the paths of Malware Project**

In [ ]:
print("Current PROJECT_ROOT:", PROJECT_ROOT)
print("\nParents:")
for i, p in enumerate(PROJECT_ROOT.parents):
    print(f"{i}: {p}")

Current PROJECT_ROOT: /Users/georgektenas/Desktop/Malware Project/code/MalDICT/LightGBM_Benchmark

Parents:
0: /Users/georgektenas/Desktop/Malware Project/code/MalDICT
1: /Users/georgektenas/Desktop/Malware Project/code
2: /Users/georgektenas/Desktop/Malware Project
3: /Users/georgektenas/Desktop
4: /Users/georgektenas
5: /Users
6: /

**Cell 3: Making the Data ROOT**

In [ ]:
ALWARE_PROJECT_ROOT = PROJECT_ROOT.parents[2]
DATA_ROOT = MALWARE_PROJECT_ROOT / "data" / "behavior_vectors_paper"

print("Malware project root:", MALWARE_PROJECT_ROOT)
print("Data root:", DATA_ROOT)

# Λίστα με μερικά .npz για να επιβεβαιώσουμε ότι τα βλέπει σωστά
npz_samples = list(DATA_ROOT.glob("*.npz"))[:20]
print(f"\nFound {len(list(DATA_ROOT.glob('*.npz')))} .npz files under DATA_ROOT")
for f in npz_samples:
    print(" -", f.name)

Malware project root: /Users/georgektenas/Desktop/Malware Project
Data root: /Users/georgektenas/Desktop/Malware Project/data/behavior_vectors_paper

Found 1192 .npz files under DATA_ROOT
 - train_part_capped298.npz
 - test_part040.npz
 - train_part259.npz
 - train_part_capped529.npz
 - train_part_capped501.npz
 - train_part265.npz
 - train_part503.npz
 - train_part_capped267.npz
 - train_part517.npz
 - train_part_capped273.npz
 - train_part_capped515.npz
 - train_part271.npz
 - train_part098.npz
 - train_part_capped059.npz
 - test_part_capped013.npz
 - test_part_capped007.npz
 - train_part_capped065.npz
 - train_part067.npz
 - train_part073.npz
 - train_part_capped071.npz

**Cell 4: Basic paths and lists train/test parts for X & Y**

In [ ]:
# Θα χρησιμοποιήσουμε ως VEC τον φάκελο behavior_vectors_paper
VEC = DATA_ROOT
BASE = MALWARE_PROJECT_ROOT

# Φόρτωση ονομάτων labels (balanced)
label_map_path = VEC / "label_map_balanced.json"
with open(label_map_path, "r") as f:
    label_names = json.load(f)["labels"]

n_labels = len(label_names)
print("Loaded balanced labels:", n_labels)

# Χρησιμοποιούμε ΜΗ capped X + balanced Y, όπως στο 03_train_eval_capped.ipynb
def non_capped_train_test_parts():
    # train_part*.npz / test_part*.npz χωρίς _capped
    train_X = sort_by_index([p for p in VEC.glob("train_part*.npz") if "_capped" not in p.name])
    test_X  = sort_by_index([p for p in VEC.glob("test_part*.npz")  if "_capped" not in p.name])

    y_train = sort_by_index(list(VEC.glob("y_train_part_balanced*.npy")))
    y_test  = sort_by_index(list(VEC.glob("y_test_part_balanced*.npy")))
    return train_X, test_X, y_train, y_test

XTRN, XTE, YTRN_BAL, YTE_BAL = non_capped_train_test_parts()

print("Train parts (X):", len(XTRN), "| Test parts (X):", len(XTE))
print("Train parts (Y):", len(YTRN_BAL), "| Test parts (Y):", len(YTE_BAL))

print("\nExample train:", XTRN[0].name, "|", YTRN_BAL[0].name)
print("Example test :", XTE[0].name,  "|", YTE_BAL[0].name)

Loaded balanced labels: 64
Train parts (X): 551 | Test parts (X): 45
Train parts (Y): 551 | Test parts (Y): 45

Example train: train_part000.npz | y_train_part_balanced000.npy
Example test : test_part000.npz | y_test_part_balanced000.npy

**Cell 5: Calculate positives per label & cap_train**

In [ ]:
pos_train = np.zeros(n_labels, dtype=np.int64)
rows_train = 0

for yp in YTRN_BAL:
    y = np.load(yp, allow_pickle=False)  # (rows, n_labels) int8
    pos_train += y.sum(axis=0).astype(np.int64)
    rows_train += y.shape[0]

min_pos = int(pos_train[pos_train > 0].min())
cap_train = 100 * max(1, min_pos)   # "no more than 100× of the min" στο TRAIN

print("Total train rows:", rows_train)
print("Min positives per label:", min_pos, "| cap_train:", cap_train)

Total train rows: 2754289
Min positives per label: 725 | cap_train: 72500

**Cell 6: RNG, sampling parameters & plan_per_part_for_label**

In [17]:
# Σταθερό RNG για επαναληψιμότητα
rng = np.random.default_rng(12345)

# Πόσα negatives ανά positive στο per-label dataset
NEG_POS_RATIO = 3     # π.χ. 3:1
# Ποσοστό του per-label dataset που κρατάμε για validation
VAL_FRACTION = 0.10   # 10%

def plan_per_part_for_label(label_idx: int, cap_pos: int):
    """
    Επιστρέφει vector με μήκος = #train parts.
    Για κάθε part λέει πόσα POS (δείγματα με y=1) θα κρατήσουμε για αυτό το label,
    έτσι ώστε συνολικά να μην ξεπεράσουμε το cap_pos.
    """
    pos_counts = []
    for yp in YTRN_BAL:
        y = np.load(yp, allow_pickle=False)  # (rows, n_labels)
        pos_counts.append(int(y[:, label_idx].sum()))
    pos_counts = np.array(pos_counts, dtype=np.int64)

    total_pos = int(pos_counts.sum())
    keep_total = min(total_pos, cap_pos)

    if total_pos == 0:
        # αν δεν υπάρχει ποτέ θετικό για αυτό το label
        return np.zeros(len(YTRN_BAL), dtype=np.int64)

    # αναλογική κατανομή ως προς το πόσα POS έχει κάθε part
    frac = pos_counts / total_pos
    plan = np.floor(frac * keep_total).astype(np.int64)

    # αν λόγω floor λείπουν μερικά POS, τα μοιράζουμε στα "πιο πλούσια" parts
    short = int(keep_total - plan.sum())
    if short > 0:
        order = np.argsort(-(frac - plan / keep_total))
        for i in order[:short]:
            plan[i] += 1

    return plan  # ανά part πόσα POS

**Cell 7: Building dataset & LightGBM training per label**

In [18]:
# Βάση για τα μοντέλα ablation – αργότερα μπορούμε να αλλάζουμε υποφακέλους ανά experiment
MODELS_DIR = VEC / "models_lgb_ablation"
MODELS_DIR.mkdir(exist_ok=True)

THRESH_PATH = VEC / "per_label_thresholds_ablation.json"

def model_path_for(label_idx: int) -> Path:
    return MODELS_DIR / f"lgb_label_{label_idx:03d}.txt"


def build_dataset_for_label(label_idx: int,
                            pos_plan_per_part,
                            feature_cols: np.ndarray | None = None):
    """
    Φτιάχνει per-label dataset με capping:
    - Για κάθε train part:
        * παίρνει k_pos POS (σύμφωνα με pos_plan_per_part)
        * παίρνει μέχρι NEG_POS_RATIO * k_pos NEG
    - Κάνει shuffle και split σε train/val (με VAL_FRACTION).
    - Αν δοθεί feature_cols, κρατάει μόνο αυτές τις στήλες.
    """
    X_list, y_list = [], []

    for pi, (xp, yp) in enumerate(zip(XTRN, YTRN_BAL)):
        Y = np.load(yp, allow_pickle=False)        # (rows, n_labels)
        X = sp.load_npz(xp)                        # csr matrix

        y_col = Y[:, label_idx].astype(np.int8)
        pos_idx = np.flatnonzero(y_col == 1)
        neg_idx = np.flatnonzero(y_col == 0)

        # πόσα POS απ' αυτό το part;
        k_pos = int(pos_plan_per_part[pi])
        if k_pos > 0 and len(pos_idx) > 0:
            pos_pick = rng.choice(pos_idx, size=min(k_pos, len(pos_idx)), replace=False)
        else:
            pos_pick = np.array([], dtype=np.int64)

        # πόσα NEG θα πάρουμε από αυτό το part;
        k_neg = int(min(len(neg_idx), NEG_POS_RATIO * max(1, len(pos_pick))))
        if k_neg > 0:
            neg_pick = rng.choice(neg_idx, size=k_neg, replace=False)
        else:
            neg_pick = np.array([], dtype=np.int64)

        pick = np.concatenate([pos_pick, neg_pick])
        if pick.size == 0:
            # τίποτα χρήσιμο από αυτό το part για αυτό το label
            del X, Y
            continue

        # subset rows (και columns αν κάνουμε ablation)
        X_part = X[pick]
        if feature_cols is not None:
            X_part = X_part[:, feature_cols]

        y_part = y_col[pick]

        X_list.append(X_part)
        y_list.append(y_part)

        del X, Y
        gc.collect()

    if not X_list:
        # κανένα δείγμα για αυτό το label
        return None, None, None, None

    X_all = sp.vstack(X_list).tocsr()
    y_all = np.concatenate(y_list).astype(np.int8)

    # shuffle
    order = rng.permutation(X_all.shape[0])
    X_all = X_all[order]
    y_all = y_all[order]

    # split σε train / val
    n_val = int(ceil(VAL_FRACTION * X_all.shape[0]))
    X_val = X_all[:n_val]
    y_val = y_all[:n_val]
    X_tr  = X_all[n_val:]
    y_tr  = y_all[n_val:]

    return X_tr, y_tr, X_val, y_val


def train_one_label(label_idx: int,
                    cap_pos: int,
                    feature_cols: np.ndarray | None = None):
    """
    Κάνει όλη τη διαδικασία για ένα label:
    - Υπολογίζει pos plan ανά part
    - Χτίζει per-label dataset (train/val)
    - Τρέχει LightGBM
    - Κάνει threshold tuning στο validation (F1)
    - Σώζει το μοντέλο & επιστρέφει το best threshold
    """
    name = label_names[label_idx]
    plan = plan_per_part_for_label(label_idx, cap_pos)

    X_tr, y_tr, X_val, y_val = build_dataset_for_label(label_idx, plan, feature_cols)
    if X_tr is None:
        print(f"[{label_idx:03d}] '{name}': no data — skipped")
        return None

    params = {
        "objective": "binary",
        "metric": "auc",
        "learning_rate": 0.05,
        "num_leaves": 31,
        "max_bin": 63,
        "feature_fraction": 0.7,
        "bagging_fraction": 0.7,
        "bagging_freq": 1,
        "min_data_in_leaf": 50,
        "min_sum_hessian_in_leaf": 1e-3,
        "num_threads": 0,
        "verbose": -1,
        "seed": 2025,
    }

    dtrain = lgb.Dataset(X_tr, label=y_tr, free_raw_data=True)
    dvalid = lgb.Dataset(X_val, label=y_val, reference=dtrain, free_raw_data=True)

    booster = lgb.train(
        params,
        dtrain,
        num_boost_round=200,
        valid_sets=[dvalid],
        valid_names=["valid"],
        callbacks=[
            lgb.early_stopping(stopping_rounds=20),
            lgb.log_evaluation(period=25),
        ],
    )

    # Threshold tuning στο validation: βρες threshold που μεγιστοποιεί F1
    val_prob = booster.predict(X_val, num_iteration=booster.best_iteration)
    thr_grid = np.linspace(0.05, 0.95, 19)
    best_thr, best_f1 = 0.5, -1.0

    for t in thr_grid:
        y_hat = (val_prob >= t).astype(np.int8)
        tp = ((y_hat == 1) & (y_val == 1)).sum()
        fp = ((y_hat == 1) & (y_val == 0)).sum()
        fn = ((y_hat == 0) & (y_val == 1)).sum()
        denom = (2 * tp + fp + fn)
        f1 = 0.0 if denom == 0 else (2 * tp) / denom

        if f1 > best_f1:
            best_f1, best_thr = f1, float(t)

    booster.save_model(str(model_path_for(label_idx)))
    print(
        f"[{label_idx:03d}] '{name}'  "
        f"best_iter={booster.best_iteration}  "
        f"best_thr={best_thr:.2f}  val_F1={best_f1:.3f}"
    )

    return best_thr

**Cell 8: Looking for all the .json files**

In [ ]:
meta_files = list(VEC.glob("*.json"))
print(f"Found {len(meta_files)} JSON files in {VEC}:\n")
for f in meta_files:
    print(" -", f.name)

# Φιλτράρουμε όσα μοιάζουν σχετικό με features
feature_meta_files = [f for f in meta_files if "feature" in f.name.lower() or "ember" in f.name.lower()]
print("\nCandidate feature-metadata files:")
for f in feature_meta_files:
    print(" -", f.name)

Found 9 JSON files in /Users/georgektenas/Desktop/Malware Project/data/behavior_vectors_paper:

 - overall_metrics_perlabel_capped.json
 - overall_metrics.json
 - label_map.json
 - label_map_balanced.json
 - overall_metrics_thr.json
 - overall_metrics_capped.json
 - best_thresholds.json
 - per_label_thresholds.json
 - best_thresholds_precision_tuned.json

Candidate feature-metadata files:

**Cell 9: Looking at the content of candidate files**

In [ ]:
# inspect content of candidate feature-metadata JSON
import itertools

for f in feature_meta_files:
    print("\n" + "="*80)
    print("File:", f.name)
    with open(f, "r") as jf:
        data = json.load(jf)

    print("Type:", type(data))

    if isinstance(data, dict):
        keys = list(data.keys())
        print("Top-level keys (up to 10):", keys[:10])

        # αν οι τιμές είναι μικρά dict ή λίστες, δείξε 2-3 παραδείγματα
        sample_items = list(itertools.islice(data.items(), 3))
        for k, v in sample_items:
            print(f"\nKey: {k}")
            print("Value type:", type(v))
            print("Preview:", str(v)[:300], "...")
    elif isinstance(data, list):
        print("List length:", len(data))
        print("First element type:", type(data[0]))
        print("First element preview:", str(data[0])[:300], "...")
    else:
        print("Unknown JSON structure, preview:", str(data)[:300], "...")

**Cell 10: Setting EMBER feature groups (0-based indices, from EMBER spec)**

In [21]:
EMBER_GROUPS = {
    "byte_hist":    np.arange(0,   256),   # 1-256
    "byte_entropy": np.arange(256, 512),   # 257-512
    "strings":      np.arange(512, 616),   # 513-616
    "general":      np.arange(616, 626),   # 617-626
    "header":       np.arange(626, 688),   # 627-688
    "sections":     np.arange(688, 943),   # 689-943
    "imports":      np.arange(943, 2223),  # 944-2223
    "exports":      np.arange(2223, 2351), # 2224-2351
    "data_dirs":    np.arange(2351, 2381), # 2352-2381
}

print("EMBER feature groups:")
total = 0
for name, idxs in EMBER_GROUPS.items():
    print(f" - {name:10s}: start={idxs[0]:4d}, end={idxs[-1]:4d}, len={len(idxs)}")
    total += len(idxs)

print("\nTotal features across all groups:", total)

EMBER feature groups:
 - byte_hist : start=   0, end= 255, len=256
 - byte_entropy: start= 256, end= 511, len=256
 - strings   : start= 512, end= 615, len=104
 - general   : start= 616, end= 625, len=10
 - header    : start= 626, end= 687, len=62
 - sections  : start= 688, end= 942, len=255
 - imports   : start= 943, end=2222, len=1280
 - exports   : start=2223, end=2350, len=128
 - data_dirs : start=2351, end=2380, len=30

Total features across all groups: 2381

**Cell 11: Helper function for ablation experiments**

In [22]:
# Cell 18: Helper συνάρτηση για ablation experiments

def cols_for_groups(group_names):
    """
    Παίρνει λίστα από ονόματα groups (π.χ. ["byte_hist", "imports"])
    και επιστρέφει ΕΝΑ sorted numpy array με όλα τα αντίστοιχα indices.
    """
    arrays = [EMBER_GROUPS[g] for g in group_names]
    cols = np.unique(np.concatenate(arrays))
    return cols

# Sanity check: αν πάρουμε ΟΛΑ τα groups, πρέπει να έχουμε 2381 features 0..2380
all_cols = cols_for_groups(list(EMBER_GROUPS.keys()))
print("All-cols length:", len(all_cols))
print("Min index:", all_cols.min(), "Max index:", all_cols.max())

All-cols length: 2381
Min index: 0 Max index: 2380

**Cell 12: Settings for ablation experiments**

In [23]:
import gc

ABLATION_EXPERIMENTS = [
    {
        "name": "all_features",
        "groups": None,  # None => όλα τα features (baseline)
    },
    {
        "name": "no_imports_exports_dirs",
        "groups": [
            "byte_hist",
            "byte_entropy",
            "strings",
            "general",
            "header",
            "sections",
        ],
    },
    {
        "name": "imports_exports_dirs_only",
        "groups": [
            "imports",
            "exports",
            "data_dirs",
        ],
    },
    {
        "name": "light_static_no_strings_no_imports",
        "groups": [
            "byte_hist",
            "byte_entropy",
            "general",
            "header",
            "sections",
        ],
    },
]

def feature_cols_for_experiment(exp):
    """
    Αν exp["groups"] είναι None -> χρησιμοποιούμε όλα τα features (feature_cols=None).
    Αλλιώς φτιάχνουμε union από τα αντίστοιχα EMBER_GROUPS.
    """
    if exp["groups"] is None:
        return None
    return cols_for_groups(exp["groups"])

print("Defined ablation experiments:")
for exp in ABLATION_EXPERIMENTS:
    g = exp["groups"]
    if g is None:
        print(f" - {exp['name']}: ALL features")
    else:
        cols = feature_cols_for_experiment(exp)
        print(f" - {exp['name']}: groups={g}, n_features={len(cols)}")

Defined ablation experiments:
 - all_features: ALL features
 - no_imports_exports_dirs: groups=['byte_hist', 'byte_entropy', 'strings', 'general', 'header', 'sections'], n_features=943
 - imports_exports_dirs_only: groups=['imports', 'exports', 'data_dirs'], n_features=1438
 - light_static_no_strings_no_imports: groups=['byte_hist', 'byte_entropy', 'general', 'header', 'sections'], n_features=839

**Cell 13: Test ablation run for only label 0**

In [24]:
import time

test_label_idx = 0
test_label_name = label_names[test_label_idx]
print(f"Ablation test for label {test_label_idx}: '{test_label_name}'")

ablation_results_single_label = []

for exp in ABLATION_EXPERIMENTS:
    exp_name = exp["name"]
    cols = feature_cols_for_experiment(exp)

    print("\n" + "="*80)
    print(f"Experiment: {exp_name}")
    if cols is None:
        print("Using ALL features")
    else:
        print(f"Using {len(cols)} features from groups: {exp['groups']}")

    t0 = time.time()
    best_thr = train_one_label(
        label_idx=test_label_idx,
        cap_pos=cap_train,
        feature_cols=cols,
    )
    elapsed_min = (time.time() - t0) / 60.0

    ablation_results_single_label.append({
        "experiment": exp_name,
        "label_idx": test_label_idx,
        "label_name": test_label_name,
        "best_threshold": best_thr,
        "time_min": elapsed_min,
    })

print("\nSummary (single-label ablation):")
for r in ablation_results_single_label:
    print(
        f"{r['experiment']:30s} | "
        f"thr={r['best_threshold']:.2f} | "
        f"time={r['time_min']:.1f} min"
    )

Ablation test for label 0: 'adware'

================================================================================
Experiment: all_features
Using ALL features
Training until validation scores don't improve for 20 rounds
[25]	valid's auc: 0.976026
[50]	valid's auc: 0.981321
[75]	valid's auc: 0.98454
[100]	valid's auc: 0.986348
[125]	valid's auc: 0.987708
[150]	valid's auc: 0.988641
[175]	valid's auc: 0.989266
[200]	valid's auc: 0.98982
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.98982
[000] 'adware'  best_iter=200  best_thr=0.50  val_F1=0.914

================================================================================
Experiment: no_imports_exports_dirs
Using 943 features from groups: ['byte_hist', 'byte_entropy', 'strings', 'general', 'header', 'sections']
Training until validation scores don't improve for 20 rounds
[25]	valid's auc: 0.973452
[50]	valid's auc: 0.979195
[75]	valid's auc: 0.982362
[100]	valid's auc: 0.984508
[125]	valid's auc: 0.986057
[150]	valid's auc: 0.987088
[175]	valid's auc: 0.987838
[200]	valid's auc: 0.988478
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.988478
[000] 'adware'  best_iter=200  best_thr=0.45  val_F1=0.912

================================================================================
Experiment: imports_exports_dirs_only
Using 1438 features from groups: ['imports', 'exports', 'data_dirs']
Training until validation scores don't improve for 20 rounds
[25]	valid's auc: 0.9715
[50]	valid's auc: 0.976155
[75]	valid's auc: 0.980227
[100]	valid's auc: 0.982508
[125]	valid's auc: 0.983905
[150]	valid's auc: 0.984985
[175]	valid's auc: 0.98602
[200]	valid's auc: 0.986637
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.986637
[000] 'adware'  best_iter=200  best_thr=0.45  val_F1=0.900

================================================================================
Experiment: light_static_no_strings_no_imports
Using 839 features from groups: ['byte_hist', 'byte_entropy', 'general', 'header', 'sections']
Training until validation scores don't improve for 20 rounds
[25]	valid's auc: 0.973138
[50]	valid's auc: 0.978457
[75]	valid's auc: 0.981656
[100]	valid's auc: 0.983818
[125]	valid's auc: 0.985403
[150]	valid's auc: 0.986525
[175]	valid's auc: 0.987299
[200]	valid's auc: 0.987956
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.987956
[000] 'adware'  best_iter=200  best_thr=0.40  val_F1=0.908

Summary (single-label ablation):
all_features                   | thr=0.50 | time=0.6 min
no_imports_exports_dirs        | thr=0.45 | time=0.5 min
imports_exports_dirs_only      | thr=0.45 | time=0.3 min
light_static_no_strings_no_imports | thr=0.40 | time=0.5 min

**Cell 14: Updated training LightGBM**

In [25]:
# Cell: Updated train_one_label -> επιστρέφει και best_F1

def train_one_label(label_idx: int,
                    cap_pos: int,
                    feature_cols: np.ndarray | None = None):
    """
    Κάνει όλη τη διαδικασία για ένα label:
    - Υπολογίζει pos plan ανά part
    - Χτίζει per-label dataset (train/val)
    - Τρέχει LightGBM
    - Κάνει threshold tuning στο validation (F1)
    - Σώζει το μοντέλο & ΕΠΙΣΤΡΕΦΕΙ (best_threshold, best_val_F1)
    """
    name = label_names[label_idx]
    plan = plan_per_part_for_label(label_idx, cap_pos)

    X_tr, y_tr, X_val, y_val = build_dataset_for_label(label_idx, plan, feature_cols)
    if X_tr is None:
        print(f"[{label_idx:03d}] '{name}': no data — skipped")
        return None, None

    params = {
        "objective": "binary",
        "metric": "auc",
        "learning_rate": 0.05,
        "num_leaves": 31,
        "max_bin": 63,
        "feature_fraction": 0.7,
        "bagging_fraction": 0.7,
        "bagging_freq": 1,
        "min_data_in_leaf": 50,
        "min_sum_hessian_in_leaf": 1e-3,
        "num_threads": 0,
        "verbose": -1,
        "seed": 2025,
    }

    dtrain = lgb.Dataset(X_tr, label=y_tr, free_raw_data=True)
    dvalid = lgb.Dataset(X_val, label=y_val, reference=dtrain, free_raw_data=True)

    booster = lgb.train(
        params,
        dtrain,
        num_boost_round=200,
        valid_sets=[dvalid],
        valid_names=["valid"],
        callbacks=[
            lgb.early_stopping(stopping_rounds=20),
            lgb.log_evaluation(period=50),
        ],
    )

    # Threshold tuning στο validation: βρες threshold που μεγιστοποιεί F1
    val_prob = booster.predict(X_val, num_iteration=booster.best_iteration)
    thr_grid = np.linspace(0.05, 0.95, 19)
    best_thr, best_f1 = 0.5, -1.0

    for t in thr_grid:
        y_hat = (val_prob >= t).astype(np.int8)
        tp = ((y_hat == 1) & (y_val == 1)).sum()
        fp = ((y_hat == 1) & (y_val == 0)).sum()
        fn = ((y_hat == 0) & (y_val == 1)).sum()
        denom = (2 * tp + fp + fn)
        f1 = 0.0 if denom == 0 else (2 * tp) / denom

        if f1 > best_f1:
            best_f1, best_thr = f1, float(t)

    booster.save_model(str(model_path_for(label_idx)))
    print(
        f"[{label_idx:03d}] '{name}'  "
        f"best_iter={booster.best_iteration}  "
        f"best_thr={best_thr:.2f}  val_F1={best_f1:.3f}"
    )

    return best_thr, best_f1

**Cell 15: Helper for full experiment for all labels**

In [26]:
# Cell: Helper για "full experiment" σε όλα τα labels

import time
import pandas as pd

RESULTS_DIR = VEC / "results_ablation"
RESULTS_DIR.mkdir(exist_ok=True)

def run_experiment_all_labels(exp_name: str, group_names):
    """
    Τρέχει ένα ablation experiment για ΟΛΑ τα labels.
    - exp_name: όνομα πειράματος (π.χ. 'light_static_no_strings_no_imports')
    - group_names: λίστα από EMBER_GROUPS keys (ή None για όλα τα features)
    Επιστρέφει pandas DataFrame με τα αποτελέσματα
    και αποθηκεύει CSV στο RESULTS_DIR.
    """
    if group_names is None:
        feature_cols = None
        n_feats = XTRN[0].shape[1]
        desc = f"ALL {n_feats} features"
    else:
        feature_cols = cols_for_groups(group_names)
        n_feats = len(feature_cols)
        desc = f"{n_feats} features from groups {group_names}"

    print("#" * 80)
    print(f"Running experiment '{exp_name}'")
    print(" ", desc)

    all_rows = []
    t0_exp = time.time()

    for li in range(n_labels):
        label_name = label_names[li]
        print(f"\n[{li:02d}/{n_labels-1:02d}] Label {li}: '{label_name}'")

        t0_label = time.time()
        best_thr, best_f1 = train_one_label(
            label_idx=li,
            cap_pos=cap_train,
            feature_cols=feature_cols,
        )
        elapsed_label = (time.time() - t0_label) / 60.0

        row = {
            "experiment": exp_name,
            "groups": None if group_names is None else ",".join(group_names),
            "n_features": n_feats,
            "label_idx": li,
            "label_name": label_name,
            "best_threshold": best_thr,
            "val_F1": best_f1,
            "time_min": elapsed_label,
        }
        all_rows.append(row)

        gc.collect()

    total_min = (time.time() - t0_exp) / 60.0
    print(f"\nExperiment '{exp_name}' finished in {total_min:.1f} minutes.")

    df = pd.DataFrame(all_rows)
    out_csv = RESULTS_DIR / f"ablation_{exp_name}.csv"
    df.to_csv(out_csv, index=False)
    print("Saved results to:", out_csv)

    return df

**Cell 16: EXPERIMENT 1**

In [27]:
#light_static_no_strings_no_imports (839 features)

exp1_name = "light_static_no_strings_no_imports"
exp1_groups = ["byte_hist", "byte_entropy", "general", "header", "sections"]

df_exp1 = run_experiment_all_labels(exp1_name, exp1_groups)
df_exp1.head()

################################################################################
Running experiment 'light_static_no_strings_no_imports'
  839 features from groups ['byte_hist', 'byte_entropy', 'general', 'header', 'sections']

[00/63] Label 0: 'adware'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.978792
[100]	valid's auc: 0.983886
[150]	valid's auc: 0.986435
[200]	valid's auc: 0.988034
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.988034
[000] 'adware'  best_iter=200  best_thr=0.40  val_F1=0.909

[01/63] Label 1: 'antiav'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.978956
[100]	valid's auc: 0.986479
[150]	valid's auc: 0.989679
[200]	valid's auc: 0.991498
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.991498
[001] 'antiav'  best_iter=200  best_thr=0.35  val_F1=0.945

[02/63] Label 2: 'antifw'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.999651
[100]	valid's auc: 0.999685
Early stopping, best iteration is:
[80]	valid's auc: 0.999688
[002] 'antifw'  best_iter=80  best_thr=0.60  val_F1=0.995

[03/63] Label 3: 'autorun'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.973848
[100]	valid's auc: 0.982364
[150]	valid's auc: 0.986031
[200]	valid's auc: 0.987923
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.987923
[003] 'autorun'  best_iter=200  best_thr=0.45  val_F1=0.911

[04/63] Label 4: 'backdoor'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.893403
[100]	valid's auc: 0.915921
[150]	valid's auc: 0.927628
[200]	valid's auc: 0.935215
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.935215
[004] 'backdoor'  best_iter=200  best_thr=0.35  val_F1=0.759

[05/63] Label 5: 'banker'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.966868
[100]	valid's auc: 0.977342
[150]	valid's auc: 0.982368
[200]	valid's auc: 0.985067
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.985067
[005] 'banker'  best_iter=200  best_thr=0.45  val_F1=0.912

[06/63] Label 6: 'bho'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.984335
[100]	valid's auc: 0.991897
[150]	valid's auc: 0.994446
[200]	valid's auc: 0.995724
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.995724
[006] 'bho'  best_iter=200  best_thr=0.35  val_F1=0.958

[07/63] Label 7: 'binder'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.980396
[100]	valid's auc: 0.986434
[150]	valid's auc: 0.988377
[200]	valid's auc: 0.989035
Did not meet early stopping. Best iteration is:
[195]	valid's auc: 0.989072
[007] 'binder'  best_iter=195  best_thr=0.40  val_F1=0.934

[08/63] Label 8: 'blocker'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.968072
[100]	valid's auc: 0.97595
[150]	valid's auc: 0.979823
[200]	valid's auc: 0.982174
Did not meet early stopping. Best iteration is:
[198]	valid's auc: 0.982185
[008] 'blocker'  best_iter=198  best_thr=0.40  val_F1=0.884

[09/63] Label 9: 'bundler'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.972272
[100]	valid's auc: 0.974411
[150]	valid's auc: 0.975614
[200]	valid's auc: 0.97618
Did not meet early stopping. Best iteration is:
[196]	valid's auc: 0.976289
[009] 'bundler'  best_iter=196  best_thr=0.25  val_F1=0.855

[10/63] Label 10: 'clicker'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.951262
[100]	valid's auc: 0.966538
[150]	valid's auc: 0.973862
[200]	valid's auc: 0.977899
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.977899
[010] 'clicker'  best_iter=200  best_thr=0.40  val_F1=0.888

[11/63] Label 11: 'coinminer'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.989569
[100]	valid's auc: 0.992801
[150]	valid's auc: 0.993776
[200]	valid's auc: 0.994372
Did not meet early stopping. Best iteration is:
[189]	valid's auc: 0.994388
[011] 'coinminer'  best_iter=189  best_thr=0.40  val_F1=0.952

[12/63] Label 12: 'constructor'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.967039
[100]	valid's auc: 0.97468
[150]	valid's auc: 0.97889
[200]	valid's auc: 0.980394
Did not meet early stopping. Best iteration is:
[199]	valid's auc: 0.980412
[012] 'constructor'  best_iter=199  best_thr=0.55  val_F1=0.893

[13/63] Label 13: 'cryptor'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.957097
[100]	valid's auc: 0.970022
[150]	valid's auc: 0.975979
[200]	valid's auc: 0.97896
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.97896
[013] 'cryptor'  best_iter=200  best_thr=0.40  val_F1=0.887

[14/63] Label 14: 'ddos'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.974363
[100]	valid's auc: 0.979417
[150]	valid's auc: 0.982047
[200]	valid's auc: 0.982719
Did not meet early stopping. Best iteration is:
[182]	valid's auc: 0.982777
[014] 'ddos'  best_iter=182  best_thr=0.70  val_F1=0.885

[15/63] Label 15: 'dialer'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.992666
[100]	valid's auc: 0.996153
[150]	valid's auc: 0.997373
[200]	valid's auc: 0.997936
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.997936
[015] 'dialer'  best_iter=200  best_thr=0.45  val_F1=0.971

[16/63] Label 16: 'downloader'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.903479
[100]	valid's auc: 0.924341
[150]	valid's auc: 0.934843
[200]	valid's auc: 0.941042
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.941042
[016] 'downloader'  best_iter=200  best_thr=0.35  val_F1=0.785

[17/63] Label 17: 'dropper'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.926019
[100]	valid's auc: 0.940281
[150]	valid's auc: 0.948032
[200]	valid's auc: 0.952967
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.952967
[017] 'dropper'  best_iter=200  best_thr=0.40  val_F1=0.798

[18/63] Label 18: 'email'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.998697
[100]	valid's auc: 0.999185
[150]	valid's auc: 0.999269
[200]	valid's auc: 0.999335
Did not meet early stopping. Best iteration is:
[199]	valid's auc: 0.999336
[018] 'email'  best_iter=199  best_thr=0.35  val_F1=0.991

[19/63] Label 19: 'exploit'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.957273
[100]	valid's auc: 0.964044
[150]	valid's auc: 0.96531
[200]	valid's auc: 0.965573
Early stopping, best iteration is:
[180]	valid's auc: 0.96591
[019] 'exploit'  best_iter=180  best_thr=0.50  val_F1=0.855

[20/63] Label 20: 'fakealert'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.974516
[100]	valid's auc: 0.982374
[150]	valid's auc: 0.985873
[200]	valid's auc: 0.98783
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.98783
[020] 'fakealert'  best_iter=200  best_thr=0.45  val_F1=0.914

[21/63] Label 21: 'fakeantivirus'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.983033
[100]	valid's auc: 0.988563
[150]	valid's auc: 0.991243
[200]	valid's auc: 0.992608
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.992608
[021] 'fakeantivirus'  best_iter=200  best_thr=0.40  val_F1=0.939

[22/63] Label 22: 'flooder'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.996391
[100]	valid's auc: 0.99804
[150]	valid's auc: 0.998558
[200]	valid's auc: 0.998812
Did not meet early stopping. Best iteration is:
[193]	valid's auc: 0.998818
[022] 'flooder'  best_iter=193  best_thr=0.35  val_F1=0.975

[23/63] Label 23: 'fraud'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.969828
[100]	valid's auc: 0.981061
[150]	valid's auc: 0.986215
[200]	valid's auc: 0.989026
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.989026
[023] 'fraud'  best_iter=200  best_thr=0.40  val_F1=0.926

[24/63] Label 24: 'ftp'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.987429
[100]	valid's auc: 0.990877
[150]	valid's auc: 0.992187
[200]	valid's auc: 0.993409
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.993409
[024] 'ftp'  best_iter=200  best_thr=0.45  val_F1=0.920

[25/63] Label 25: 'gamehack'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.996434
Early stopping, best iteration is:
[45]	valid's auc: 0.996654
[025] 'gamehack'  best_iter=45  best_thr=0.40  val_F1=0.972

[26/63] Label 26: 'gamethief'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.977678
[100]	valid's auc: 0.98327
[150]	valid's auc: 0.985721
[200]	valid's auc: 0.986956
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.986956
[026] 'gamethief'  best_iter=200  best_thr=0.40  val_F1=0.918

[27/63] Label 27: 'hacktool'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.956271
[100]	valid's auc: 0.969847
[150]	valid's auc: 0.975999
[200]	valid's auc: 0.979431
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.979431
[027] 'hacktool'  best_iter=200  best_thr=0.40  val_F1=0.875

[28/63] Label 28: 'hoax'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.991135
[100]	valid's auc: 0.995659
[150]	valid's auc: 0.996921
[200]	valid's auc: 0.997407
Did not meet early stopping. Best iteration is:
[199]	valid's auc: 0.997409
[028] 'hoax'  best_iter=199  best_thr=0.50  val_F1=0.981

[29/63] Label 29: 'hotbar'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.99964
Early stopping, best iteration is:
[50]	valid's auc: 0.99964
[029] 'hotbar'  best_iter=50  best_thr=0.40  val_F1=0.990

[30/63] Label 30: 'injector'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.948058
[100]	valid's auc: 0.961443
[150]	valid's auc: 0.968089
[200]	valid's auc: 0.972141
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.972141
[030] 'injector'  best_iter=200  best_thr=0.40  val_F1=0.855

[31/63] Label 31: 'installer'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.999409
Early stopping, best iteration is:
[42]	valid's auc: 0.999474
[031] 'installer'  best_iter=42  best_thr=0.20  val_F1=0.991

[32/63] Label 32: 'ircbot'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.959481
[100]	valid's auc: 0.971312
[150]	valid's auc: 0.976957
[200]	valid's auc: 0.980268
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.980268
[032] 'ircbot'  best_iter=200  best_thr=0.35  val_F1=0.887

[33/63] Label 33: 'joke'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.985055
[100]	valid's auc: 0.989716
[150]	valid's auc: 0.991646
Early stopping, best iteration is:
[175]	valid's auc: 0.992152
[033] 'joke'  best_iter=175  best_thr=0.30  val_F1=0.944

[34/63] Label 34: 'keygen'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.983775
[100]	valid's auc: 0.989118
[150]	valid's auc: 0.991316
[200]	valid's auc: 0.992074
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.992074
[034] 'keygen'  best_iter=200  best_thr=0.60  val_F1=0.930

[35/63] Label 35: 'keylogger'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.960201
[100]	valid's auc: 0.971795
[150]	valid's auc: 0.977659
[200]	valid's auc: 0.981093
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.981093
[035] 'keylogger'  best_iter=200  best_thr=0.40  val_F1=0.888

[36/63] Label 36: 'lockscreen'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.972612
[100]	valid's auc: 0.982171
[150]	valid's auc: 0.985096
[200]	valid's auc: 0.98645
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.98645
[036] 'lockscreen'  best_iter=200  best_thr=0.45  val_F1=0.906

[37/63] Label 37: 'net'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.985728
[100]	valid's auc: 0.986982
[150]	valid's auc: 0.987318
[200]	valid's auc: 0.987538
Did not meet early stopping. Best iteration is:
[198]	valid's auc: 0.98755
[037] 'net'  best_iter=198  best_thr=0.55  val_F1=0.910

[38/63] Label 38: 'nettool'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.992846
[100]	valid's auc: 0.994641
[150]	valid's auc: 0.995242
Early stopping, best iteration is:
[137]	valid's auc: 0.995671
[038] 'nettool'  best_iter=137  best_thr=0.20  val_F1=0.968

[39/63] Label 39: 'nuker'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.983712
[100]	valid's auc: 0.988464
[150]	valid's auc: 0.990725
Early stopping, best iteration is:
[156]	valid's auc: 0.991417
[039] 'nuker'  best_iter=156  best_thr=0.50  val_F1=0.922

[40/63] Label 40: 'packed'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.937461
[100]	valid's auc: 0.951805
[150]	valid's auc: 0.958896
[200]	valid's auc: 0.962905
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.962905
[040] 'packed'  best_iter=200  best_thr=0.45  val_F1=0.826

[41/63] Label 41: 'passwordstealer'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.941466
[100]	valid's auc: 0.955844
[150]	valid's auc: 0.96298
[200]	valid's auc: 0.967329
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.967329
[041] 'passwordstealer'  best_iter=200  best_thr=0.35  val_F1=0.854

[42/63] Label 42: 'patcher'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.964147
[100]	valid's auc: 0.973901
[150]	valid's auc: 0.978059
[200]	valid's auc: 0.980138
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.980138
[042] 'patcher'  best_iter=200  best_thr=0.45  val_F1=0.895

[43/63] Label 43: 'porn'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.995754
[100]	valid's auc: 0.996873
[150]	valid's auc: 0.997058
Early stopping, best iteration is:
[163]	valid's auc: 0.997121
[043] 'porn'  best_iter=163  best_thr=0.30  val_F1=0.970

[44/63] Label 44: 'proxy'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.96245
[100]	valid's auc: 0.975625
[150]	valid's auc: 0.980316
[200]	valid's auc: 0.983474
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.983474
[044] 'proxy'  best_iter=200  best_thr=0.45  val_F1=0.905

[45/63] Label 45: 'pua'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.962964
[100]	valid's auc: 0.967172
[150]	valid's auc: 0.969407
[200]	valid's auc: 0.970657
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.970657
[045] 'pua'  best_iter=200  best_thr=0.40  val_F1=0.849

[46/63] Label 46: 'rahack'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.983731
[100]	valid's auc: 0.984161
[150]	valid's auc: 0.984381
Early stopping, best iteration is:
[155]	valid's auc: 0.984396
[046] 'rahack'  best_iter=155  best_thr=0.40  val_F1=0.913

[47/63] Label 47: 'ransom'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.972881
[100]	valid's auc: 0.98125
[150]	valid's auc: 0.985783
[200]	valid's auc: 0.988424
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.988424
[047] 'ransom'  best_iter=200  best_thr=0.45  val_F1=0.920

[48/63] Label 48: 'rat'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.99087
[100]	valid's auc: 0.993913
[150]	valid's auc: 0.99483
Early stopping, best iteration is:
[155]	valid's auc: 0.994892
[048] 'rat'  best_iter=155  best_thr=0.30  val_F1=0.956

[49/63] Label 49: 'riskware'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.96648
[100]	valid's auc: 0.976086
[150]	valid's auc: 0.980659
[200]	valid's auc: 0.9832
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.9832
[049] 'riskware'  best_iter=200  best_thr=0.35  val_F1=0.889

[50/63] Label 50: 'rootkit'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.990079
[100]	valid's auc: 0.994129
[150]	valid's auc: 0.995636
[200]	valid's auc: 0.996309
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.996309
[050] 'rootkit'  best_iter=200  best_thr=0.30  val_F1=0.973

[51/63] Label 51: 'screensaver'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.998437
[100]	valid's auc: 0.998652
[150]	valid's auc: 0.998653
Early stopping, best iteration is:
[130]	valid's auc: 0.998685
[051] 'screensaver'  best_iter=130  best_thr=0.65  val_F1=0.980

[52/63] Label 52: 'selfdel'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.997223
[100]	valid's auc: 0.998809
[150]	valid's auc: 0.999089
Early stopping, best iteration is:
[137]	valid's auc: 0.99913
[052] 'selfdel'  best_iter=137  best_thr=0.40  val_F1=0.991

[53/63] Label 53: 'servstart'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.998138
[100]	valid's auc: 0.999235
[150]	valid's auc: 0.999529
[200]	valid's auc: 0.999656
Did not meet early stopping. Best iteration is:
[195]	valid's auc: 0.999659
[053] 'servstart'  best_iter=195  best_thr=0.40  val_F1=0.985

[54/63] Label 54: 'spam'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.987347
[100]	valid's auc: 0.992378
[150]	valid's auc: 0.993954
[200]	valid's auc: 0.994444
Did not meet early stopping. Best iteration is:
[192]	valid's auc: 0.994444
[054] 'spam'  best_iter=192  best_thr=0.45  val_F1=0.954

[55/63] Label 55: 'spyware'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.910883
[100]	valid's auc: 0.929558
[150]	valid's auc: 0.939796
[200]	valid's auc: 0.946779
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.946779
[055] 'spyware'  best_iter=200  best_thr=0.40  val_F1=0.791

[56/63] Label 56: 'startpage'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.982707
[100]	valid's auc: 0.990844
[150]	valid's auc: 0.993564
[200]	valid's auc: 0.994724
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.994724
[056] 'startpage'  best_iter=200  best_thr=0.40  val_F1=0.952

[57/63] Label 57: 'stealer'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.991221
[100]	valid's auc: 0.995019
[150]	valid's auc: 0.995895
Early stopping, best iteration is:
[154]	valid's auc: 0.996016
[057] 'stealer'  best_iter=154  best_thr=0.35  val_F1=0.964

[58/63] Label 58: 'toolbar'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.995279
[100]	valid's auc: 0.996558
Early stopping, best iteration is:
[91]	valid's auc: 0.996708
[058] 'toolbar'  best_iter=91  best_thr=0.50  val_F1=0.964

[59/63] Label 59: 'vbinject'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.995028
[100]	valid's auc: 0.997056
[150]	valid's auc: 0.997527
[200]	valid's auc: 0.997752
Did not meet early stopping. Best iteration is:
[199]	valid's auc: 0.997752
[059] 'vbinject'  best_iter=199  best_thr=0.50  val_F1=0.967

[60/63] Label 60: 'virtool'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.943095
[100]	valid's auc: 0.952495
[150]	valid's auc: 0.956621
Early stopping, best iteration is:
[171]	valid's auc: 0.957552
[060] 'virtool'  best_iter=171  best_thr=0.35  val_F1=0.841

[61/63] Label 61: 'virus'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.975368

,experiment,groups,n_features,label_idx,label_name,best_threshold,val_F1,time_min
0,light_static_no_strings_no_imports,"byte_hist,byte_entropy,general,header,sections",839,0,adware,0.40,0.908793,0.488149
1,light_static_no_strings_no_imports,"byte_hist,byte_entropy,general,header,sections",839,1,antiav,0.35,0.945106,0.507878
2,light_static_no_strings_no_imports,"byte_hist,byte_entropy,general,header,sections",839,2,antifw,0.60,0.995100,0.394165
3,light_static_no_strings_no_imports,"byte_hist,byte_entropy,general,header,sections",839,3,autorun,0.45,0.911220,0.500875
4,light_static_no_strings_no_imports,"byte_hist,byte_entropy,general,header,sections",839,4,backdoor,0.35,0.758691,0.495765

**Cell 17: Overall Micro / Macro / Weighted metrics for EXPERIMENT 1 on VAL SET**

In [28]:
from sklearn.metrics import roc_auc_score
import numpy as np
import pandas as pd

# Ορισμός των groups για το Experiment 1 (όπως πριν)
exp1_groups = ["byte_hist", "byte_entropy", "general", "header", "sections"]
feature_cols_exp1 = cols_for_groups(exp1_groups)

def overall_metrics_from_df(df_results, feature_cols):
    """
    Υπολογίζει συνολικό Precision / Recall / F1 / AUC
    (micro, macro, weighted) πάνω στα validation sets ΚΑΘΕ label,
    χρησιμοποιώντας τα ήδη εκπαιδευμένα LightGBM + thresholds του df_results.
    """

    TP_total = 0
    FP_total = 0
    FN_total = 0

    precisions = []
    recalls = []
    f1s = []
    aucs = []
    supports = []          # #positives ανά label
    all_y = []             # για micro AUC (flatten)
    all_p = []             # για micro AUC

    # Προσοχή: να έχουμε σταθερό RNG για reproducibility
    global rng
    rng = np.random.default_rng(2025)

    for li in range(n_labels):
        name = label_names[li]

        row = df_results.loc[df_results["label_idx"] == li]
        if row.empty:
            print(f"⚠️  Δεν βρέθηκε threshold για label {li} – το αγνοώ.")
            continue

        thr = float(row["best_threshold"].iloc[0])

        # Φτιάχνουμε το dataset για το συγκεκριμένο label (όπως στο training)
        plan = plan_per_part_for_label(li, cap_train)
        X_tr, y_tr, X_val, y_val = build_dataset_for_label(li, plan, feature_cols)

        if X_val is None or y_val is None:
            print(f"⚠️  Label {li} ('{name}') δεν έχει validation δείγματα – skip.")
            continue

        # Φορτώνουμε το ήδη εκπαιδευμένο μοντέλο
        booster = lgb.Booster(model_file=str(model_path_for(li)))
        prob = booster.predict(X_val, num_iteration=booster.best_iteration)
        y_hat = (prob >= thr).astype(np.int8)

        # TP/FP/FN per-label
        tp = int(((y_hat == 1) & (y_val == 1)).sum())
        fp = int(((y_hat == 1) & (y_val == 0)).sum())
        fn = int(((y_hat == 0) & (y_val == 1)).sum())
        tn = int(((y_hat == 0) & (y_val == 0)).sum())

        support = tp + fn  # #positive examples για το label

        # Per-label metrics
        prec = 0.0 if (tp + fp) == 0 else tp / (tp + fp)
        rec  = 0.0 if (tp + fn) == 0 else tp / (tp + fn)
        denom = 2*tp + fp + fn
        f1   = 0.0 if denom == 0 else (2*tp) / denom

        try:
            auc = roc_auc_score(y_val, prob)
        except ValueError:
            auc = np.nan  # αν το label έχει μόνο μία κλάση στο val set

        precisions.append(prec)
        recalls.append(rec)
        f1s.append(f1)
        aucs.append(auc)
        supports.append(support)

        TP_total += tp
        FP_total += fp
        FN_total += fn

        # για micro AUC (flatten όλων των (y, prob))
        all_y.append(y_val.astype(np.int8).ravel())
        all_p.append(prob.ravel())

        gc.collect()

    precisions = np.array(precisions)
    recalls    = np.array(recalls)
    f1s        = np.array(f1s)
    aucs       = np.array(aucs)
    supports   = np.array(supports, dtype=float)

    # ----- Macro -----
    macro_P   = np.nanmean(precisions)
    macro_R   = np.nanmean(recalls)
    macro_F1  = np.nanmean(f1s)
    macro_AUC = np.nanmean(aucs)

    # ----- Weighted (βάρη = #positives ανά label) -----
    w = supports / supports.sum()
    weighted_P   = np.nansum(precisions * w)
    weighted_R   = np.nansum(recalls * w)
    weighted_F1  = np.nansum(f1s * w)
    weighted_AUC = np.nansum(aucs * w)

    # ----- Micro (από συνολικά TP/FP/FN) -----
    micro_P = 0.0 if (TP_total + FP_total) == 0 else TP_total / (TP_total + FP_total)
    micro_R = 0.0 if (TP_total + FN_total) == 0 else TP_total / (TP_total + FN_total)
    denom   = 2*TP_total + FP_total + FN_total
    micro_F1 = 0.0 if denom == 0 else (2*TP_total) / denom

    # Micro AUC: flatten όλων των (y, prob)
    all_y_flat = np.concatenate(all_y)
    all_p_flat = np.concatenate(all_p)
    try:
        micro_AUC = roc_auc_score(all_y_flat, all_p_flat)
    except ValueError:
        micro_AUC = np.nan

    # Φτιάχνουμε ωραίο DataFrame όπως στο screenshot
    table = pd.DataFrame(
        index=["Precision", "Recall", "F1-score", "AUC"],
        columns=["Micro", "Macro", "Weighted"],
        data=[
            [micro_P, macro_P, weighted_P],
            [micro_R, macro_R, weighted_R],
            [micro_F1, macro_F1, weighted_F1],
            [micro_AUC, macro_AUC, weighted_AUC],
        ]
    ).round(4)

    return table

metrics_exp1 = overall_metrics_from_df(df_exp1, feature_cols_exp1)
metrics_exp1

            Micro   Macro  Weighted
Precision  0.9083  0.9242    0.9098
Recall     0.9192  0.9398    0.9192
F1-score   0.9137  0.9313    0.9138
AUC        0.9894  0.9893    0.9845

**Cell 18: Overall metrics on TEST set**

In [ ]:
from sklearn.metrics import precision_recall_fscore_support, roc_auc_score

def overall_test_metrics_for_experiment(df_exp, feature_cols, exp_name):
    # 1) πάρε per-label thresholds από το df_exp (από το ablation run)
    thr_map = {
        int(row["label_idx"]): float(row["best_threshold"])
        for _, row in df_exp.iterrows()
    }

    true_all, prob_all, pred_all = [], [], []

    for pi, (xp, yp) in enumerate(zip(XTE, YTE_BAL)):
        print(f"[test:{exp_name}] part {pi+1}/{len(XTE)} ...")
        X_full = sp.load_npz(xp)
        Y = np.load(yp, allow_pickle=False).astype(np.int8)

        # κρατάμε μόνο τις στήλες του experiment (π.χ. 839 features)
        X = X_full[:, feature_cols]

        probs = np.zeros((X.shape[0], n_labels), dtype=np.float32)
        preds = np.zeros((X.shape[0], n_labels), dtype=np.int8)

           
    for li in range(n_labels):
        # Φορτώνουμε το μοντέλο του συγκεκριμένου label από τον ίδιο φάκελο
        # που χρησιμοποίησε η train_one_label / model_path_for(li)
        model_path = model_path_for(li)
        booster = lgb.Booster(model_file=str(model_path))

        # καλό είναι να χρησιμοποιούμε το best_iteration
        p = booster.predict(X, num_iteration=booster.best_iteration)
        probs[:, li] = p

        thr = thr_map.get(li, 0.5)
        preds[:, li] = (p >= thr).astype(np.int8)

        true_all.append(Y)
        prob_all.append(probs)
        pred_all.append(preds)

    y_true = np.vstack(true_all)
    y_prob = np.vstack(prob_all)
    y_pred = np.vstack(pred_all)

    # Micro / Macro / Weighted Precision–Recall–F1 (όπως στο 03_train_eval_capped)
    micro_P, micro_R, micro_F1, _ = precision_recall_fscore_support(
        y_true, y_pred, average="micro", zero_division=0
    )
    macro_P, macro_R, macro_F1, _ = precision_recall_fscore_support(
        y_true, y_pred, average="macro", zero_division=0
    )
    weighted_P, weighted_R, weighted_F1, _ = precision_recall_fscore_support(
        y_true, y_pred, average="weighted", zero_division=0
    )

    try:
        micro_AUC = roc_auc_score(y_true, y_prob, average="micro")
    except ValueError:
        micro_AUC = np.nan
    try:
        macro_AUC = roc_auc_score(y_true, y_prob, average="macro")
    except ValueError:
        macro_AUC = np.nan
    try:
        weighted_AUC = roc_auc_score(y_true, y_prob, average="weighted")
    except ValueError:
        weighted_AUC = np.nan

    table = pd.DataFrame(
        [
            [micro_P,  macro_P,  weighted_P],
            [micro_R,  macro_R,  weighted_R],
            [micro_F1, macro_F1, weighted_F1],
            [micro_AUC, macro_AUC, weighted_AUC],
        ],
        index=["Precision", "Recall", "F1-score", "AUC"],
        columns=["Micro", "Macro", "Weighted"],
    ).round(4)

    out_csv = DATA_ROOT / "results_ablation" / f"overall_test_metrics_{exp_name}.csv"
    table.to_csv(out_csv)
    print("Saved TEST metrics ->", out_csv)

    return table

In [33]:
test_metrics_exp1 = overall_test_metrics_for_experiment(df_exp1, feature_cols_exp1, exp1_name)
test_metrics_exp1

[test:light_static_no_strings_no_imports] part 1/45 ...
[test:light_static_no_strings_no_imports] part 2/45 ...
[test:light_static_no_strings_no_imports] part 3/45 ...
[test:light_static_no_strings_no_imports] part 4/45 ...
[test:light_static_no_strings_no_imports] part 5/45 ...
[test:light_static_no_strings_no_imports] part 6/45 ...
[test:light_static_no_strings_no_imports] part 7/45 ...
[test:light_static_no_strings_no_imports] part 8/45 ...
[test:light_static_no_strings_no_imports] part 9/45 ...
[test:light_static_no_strings_no_imports] part 10/45 ...
[test:light_static_no_strings_no_imports] part 11/45 ...
[test:light_static_no_strings_no_imports] part 12/45 ...
[test:light_static_no_strings_no_imports] part 13/45 ...
[test:light_static_no_strings_no_imports] part 14/45 ...
[test:light_static_no_strings_no_imports] part 15/45 ...
[test:light_static_no_strings_no_imports] part 16/45 ...
[test:light_static_no_strings_no_imports] part 17/45 ...
[test:light_static_no_strings_no_imports] part 18/45 ...
[test:light_static_no_strings_no_imports] part 19/45 ...
[test:light_static_no_strings_no_imports] part 20/45 ...
[test:light_static_no_strings_no_imports] part 21/45 ...
[test:light_static_no_strings_no_imports] part 22/45 ...
[test:light_static_no_strings_no_imports] part 23/45 ...
[test:light_static_no_strings_no_imports] part 24/45 ...
[test:light_static_no_strings_no_imports] part 25/45 ...
[test:light_static_no_strings_no_imports] part 26/45 ...
[test:light_static_no_strings_no_imports] part 27/45 ...
[test:light_static_no_strings_no_imports] part 28/45 ...
[test:light_static_no_strings_no_imports] part 29/45 ...
[test:light_static_no_strings_no_imports] part 30/45 ...
[test:light_static_no_strings_no_imports] part 31/45 ...
[test:light_static_no_strings_no_imports] part 32/45 ...
[test:light_static_no_strings_no_imports] part 33/45 ...
[test:light_static_no_strings_no_imports] part 34/45 ...
[test:light_static_no_strings_no_imports] part 35/45 ...
[test:light_static_no_strings_no_imports] part 36/45 ...
[test:light_static_no_strings_no_imports] part 37/45 ...
[test:light_static_no_strings_no_imports] part 38/45 ...
[test:light_static_no_strings_no_imports] part 39/45 ...
[test:light_static_no_strings_no_imports] part 40/45 ...
[test:light_static_no_strings_no_imports] part 41/45 ...
[test:light_static_no_strings_no_imports] part 42/45 ...
[test:light_static_no_strings_no_imports] part 43/45 ...
[test:light_static_no_strings_no_imports] part 44/45 ...
[test:light_static_no_strings_no_imports] part 45/45 ...

/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(

Saved TEST metrics -> /Users/georgektenas/Desktop/Malware Project/data/behavior_vectors_paper/results_ablation/overall_test_metrics_light_static_no_strings_no_imports.csv

/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(

            Micro   Macro  Weighted
Precision  0.0991  0.0934    0.3903
Recall     0.2435  0.2630    0.2435
F1-score   0.1409  0.0933    0.2548
AUC        0.8063     NaN    0.6288

**Cell 19: Training for EXPERIMENT 2**

In [34]:
# κρατάμε όλα τα groups εκτός από header + sections
# groups: byte_hist, byte_entropy, general, strings, imports, exports, data_dirs

exp2_name = "all_except_header_sections"
exp2_groups = [
    "byte_hist",
    "byte_entropy",
    "general",
    "strings",
    "imports",
    "exports",
    "data_dirs",
]

# Χρησιμοποιούμε τον ίδιο helper όπως στο Πείραμα 1
feature_cols_exp2 = cols_for_groups(exp2_groups)

df_exp2 = run_experiment_all_labels(exp2_name, exp2_groups)
df_exp2.head()

################################################################################
Running experiment 'all_except_header_sections'
  2064 features from groups ['byte_hist', 'byte_entropy', 'general', 'strings', 'imports', 'exports', 'data_dirs']

[00/63] Label 0: 'adware'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.980137
[100]	valid's auc: 0.9855
[150]	valid's auc: 0.987933
[200]	valid's auc: 0.989254
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.989254
[000] 'adware'  best_iter=200  best_thr=0.45  val_F1=0.912

[01/63] Label 1: 'antiav'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.9754
[100]	valid's auc: 0.984256
[150]	valid's auc: 0.988111
[200]	valid's auc: 0.989912
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.989912
[001] 'antiav'  best_iter=200  best_thr=0.35  val_F1=0.939

[02/63] Label 2: 'antifw'
Training until validation scores don't improve for 20 rounds
Early stopping, best iteration is:
[5]	valid's auc: 0.999793
[002] 'antifw'  best_iter=5  best_thr=0.30  val_F1=0.996

[03/63] Label 3: 'autorun'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.976508
[100]	valid's auc: 0.983522
[150]	valid's auc: 0.987042
[200]	valid's auc: 0.988887
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.988887
[003] 'autorun'  best_iter=200  best_thr=0.40  val_F1=0.923

[04/63] Label 4: 'backdoor'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.900452
[100]	valid's auc: 0.92018
[150]	valid's auc: 0.930916
[200]	valid's auc: 0.937845
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.937845
[004] 'backdoor'  best_iter=200  best_thr=0.35  val_F1=0.764

[05/63] Label 5: 'banker'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.97206
[100]	valid's auc: 0.981479
[150]	valid's auc: 0.985532
[200]	valid's auc: 0.98803
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.98803
[005] 'banker'  best_iter=200  best_thr=0.45  val_F1=0.927

[06/63] Label 6: 'bho'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.987649
[100]	valid's auc: 0.992945
[150]	valid's auc: 0.994981
[200]	valid's auc: 0.995968
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.995968
[006] 'bho'  best_iter=200  best_thr=0.35  val_F1=0.960

[07/63] Label 7: 'binder'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.987402
[100]	valid's auc: 0.990673
[150]	valid's auc: 0.992294
[200]	valid's auc: 0.992858
Did not meet early stopping. Best iteration is:
[198]	valid's auc: 0.992887
[007] 'binder'  best_iter=198  best_thr=0.50  val_F1=0.948

[08/63] Label 8: 'blocker'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.949455
[100]	valid's auc: 0.961844
[150]	valid's auc: 0.968103
[200]	valid's auc: 0.971446
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.971446
[008] 'blocker'  best_iter=200  best_thr=0.40  val_F1=0.865

[09/63] Label 9: 'bundler'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.973365
[100]	valid's auc: 0.97621
Early stopping, best iteration is:
[109]	valid's auc: 0.97663
[009] 'bundler'  best_iter=109  best_thr=0.45  val_F1=0.842

[10/63] Label 10: 'clicker'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.957715
[100]	valid's auc: 0.970083
[150]	valid's auc: 0.976428
[200]	valid's auc: 0.979787
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.979787
[010] 'clicker'  best_iter=200  best_thr=0.40  val_F1=0.898

[11/63] Label 11: 'coinminer'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.984691
[100]	valid's auc: 0.991312
[150]	valid's auc: 0.992949
[200]	valid's auc: 0.994012
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.994012
[011] 'coinminer'  best_iter=200  best_thr=0.45  val_F1=0.950

[12/63] Label 12: 'constructor'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.972399
[100]	valid's auc: 0.980378
[150]	valid's auc: 0.983029
[200]	valid's auc: 0.984296
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.984296
[012] 'constructor'  best_iter=200  best_thr=0.35  val_F1=0.900

[13/63] Label 13: 'cryptor'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.96066
[100]	valid's auc: 0.973146
[150]	valid's auc: 0.978616
[200]	valid's auc: 0.981303
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.981303
[013] 'cryptor'  best_iter=200  best_thr=0.45  val_F1=0.898

[14/63] Label 14: 'ddos'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.970896
[100]	valid's auc: 0.977412
[150]	valid's auc: 0.978396
Early stopping, best iteration is:
[135]	valid's auc: 0.97862
[014] 'ddos'  best_iter=135  best_thr=0.30  val_F1=0.912

[15/63] Label 15: 'dialer'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.992286
[100]	valid's auc: 0.996744
[150]	valid's auc: 0.997873
[200]	valid's auc: 0.998457
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.998457
[015] 'dialer'  best_iter=200  best_thr=0.40  val_F1=0.982

[16/63] Label 16: 'downloader'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.904415
[100]	valid's auc: 0.926597
[150]	valid's auc: 0.937837
[200]	valid's auc: 0.94385
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.94385
[016] 'downloader'  best_iter=200  best_thr=0.35  val_F1=0.794

[17/63] Label 17: 'dropper'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.929249
[100]	valid's auc: 0.942331
[150]	valid's auc: 0.949643
[200]	valid's auc: 0.954334
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.954334
[017] 'dropper'  best_iter=200  best_thr=0.35  val_F1=0.807

[18/63] Label 18: 'email'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.998214
[100]	valid's auc: 0.998948
[150]	valid's auc: 0.9992
[200]	valid's auc: 0.999305
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.999305
[018] 'email'  best_iter=200  best_thr=0.30  val_F1=0.990

[19/63] Label 19: 'exploit'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.956935
[100]	valid's auc: 0.963451
[150]	valid's auc: 0.965563
Early stopping, best iteration is:
[167]	valid's auc: 0.966113
[019] 'exploit'  best_iter=167  best_thr=0.30  val_F1=0.848

[20/63] Label 20: 'fakealert'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.971176
[100]	valid's auc: 0.98049
[150]	valid's auc: 0.984934
[200]	valid's auc: 0.987326
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.987326
[020] 'fakealert'  best_iter=200  best_thr=0.40  val_F1=0.913

[21/63] Label 21: 'fakeantivirus'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.982314
[100]	valid's auc: 0.988351
[150]	valid's auc: 0.991292
[200]	valid's auc: 0.992849
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.992849
[021] 'fakeantivirus'  best_iter=200  best_thr=0.40  val_F1=0.938

[22/63] Label 22: 'flooder'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.996387
[100]	valid's auc: 0.997658
[150]	valid's auc: 0.998151
[200]	valid's auc: 0.998415
Did not meet early stopping. Best iteration is:
[197]	valid's auc: 0.998431
[022] 'flooder'  best_iter=197  best_thr=0.45  val_F1=0.978

[23/63] Label 23: 'fraud'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.963984
[100]	valid's auc: 0.978382
[150]	valid's auc: 0.984304
[200]	valid's auc: 0.987802
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.987802
[023] 'fraud'  best_iter=200  best_thr=0.35  val_F1=0.924

[24/63] Label 24: 'ftp'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.978804
[100]	valid's auc: 0.986579
[150]	valid's auc: 0.989402
Early stopping, best iteration is:
[154]	valid's auc: 0.990143
[024] 'ftp'  best_iter=154  best_thr=0.30  val_F1=0.965

[25/63] Label 25: 'gamehack'
Training until validation scores don't improve for 20 rounds
Early stopping, best iteration is:
[21]	valid's auc: 0.996528
[025] 'gamehack'  best_iter=21  best_thr=0.30  val_F1=0.959

[26/63] Label 26: 'gamethief'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.980929
[100]	valid's auc: 0.986619
[150]	valid's auc: 0.988783
[200]	valid's auc: 0.989885
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.989885
[026] 'gamethief'  best_iter=200  best_thr=0.35  val_F1=0.930

[27/63] Label 27: 'hacktool'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.955163
[100]	valid's auc: 0.969378
[150]	valid's auc: 0.975316
[200]	valid's auc: 0.978516
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.978516
[027] 'hacktool'  best_iter=200  best_thr=0.35  val_F1=0.878

[28/63] Label 28: 'hoax'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.989972
[100]	valid's auc: 0.996096
[150]	valid's auc: 0.997576
[200]	valid's auc: 0.998169
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.998169
[028] 'hoax'  best_iter=200  best_thr=0.50  val_F1=0.980

[29/63] Label 29: 'hotbar'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.999716
Early stopping, best iteration is:
[63]	valid's auc: 0.999727
[029] 'hotbar'  best_iter=63  best_thr=0.50  val_F1=0.990

[30/63] Label 30: 'injector'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.952321
[100]	valid's auc: 0.964754
[150]	valid's auc: 0.970689
[200]	valid's auc: 0.974356
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.974356
[030] 'injector'  best_iter=200  best_thr=0.40  val_F1=0.863

[31/63] Label 31: 'installer'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.999908
Early stopping, best iteration is:
[73]	valid's auc: 0.999934
[031] 'installer'  best_iter=73  best_thr=0.60  val_F1=0.996

[32/63] Label 32: 'ircbot'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.963743
[100]	valid's auc: 0.975144
[150]	valid's auc: 0.980856
[200]	valid's auc: 0.98388
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.98388
[032] 'ircbot'  best_iter=200  best_thr=0.35  val_F1=0.894

[33/63] Label 33: 'joke'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.983712
[100]	valid's auc: 0.991344
[150]	valid's auc: 0.993277
Early stopping, best iteration is:
[148]	valid's auc: 0.993363
[033] 'joke'  best_iter=148  best_thr=0.40  val_F1=0.941

[34/63] Label 34: 'keygen'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.993026
[100]	valid's auc: 0.995687
[150]	valid's auc: 0.996606
[200]	valid's auc: 0.997152
Did not meet early stopping. Best iteration is:
[197]	valid's auc: 0.997159
[034] 'keygen'  best_iter=197  best_thr=0.30  val_F1=0.957

[35/63] Label 35: 'keylogger'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.970289
[100]	valid's auc: 0.980591
[150]	valid's auc: 0.98549
[200]	valid's auc: 0.988224
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.988224
[035] 'keylogger'  best_iter=200  best_thr=0.40  val_F1=0.916

[36/63] Label 36: 'lockscreen'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.980472
[100]	valid's auc: 0.986076
[150]	valid's auc: 0.987841
[200]	valid's auc: 0.988687
Did not meet early stopping. Best iteration is:
[188]	valid's auc: 0.988752
[036] 'lockscreen'  best_iter=188  best_thr=0.50  val_F1=0.957

[37/63] Label 37: 'net'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.98435
[100]	valid's auc: 0.986325
[150]	valid's auc: 0.98679
Early stopping, best iteration is:
[156]	valid's auc: 0.98681
[037] 'net'  best_iter=156  best_thr=0.45  val_F1=0.908

[38/63] Label 38: 'nettool'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.988034
[100]	valid's auc: 0.990717
Early stopping, best iteration is:
[116]	valid's auc: 0.991252
[038] 'nettool'  best_iter=116  best_thr=0.35  val_F1=0.962

[39/63] Label 39: 'nuker'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.988191
[100]	valid's auc: 0.993327
[150]	valid's auc: 0.99504
[200]	valid's auc: 0.996269
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.996269
[039] 'nuker'  best_iter=200  best_thr=0.55  val_F1=0.954

[40/63] Label 40: 'packed'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.938412
[100]	valid's auc: 0.951474
[150]	valid's auc: 0.958611
[200]	valid's auc: 0.96275
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.96275
[040] 'packed'  best_iter=200  best_thr=0.40  val_F1=0.823

[41/63] Label 41: 'passwordstealer'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.943589
[100]	valid's auc: 0.957681
[150]	valid's auc: 0.964811
[200]	valid's auc: 0.969112
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.969112
[041] 'passwordstealer'  best_iter=200  best_thr=0.35  val_F1=0.865

[42/63] Label 42: 'patcher'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.965799
[100]	valid's auc: 0.97435
[150]	valid's auc: 0.977582
[200]	valid's auc: 0.978881
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.978881
[042] 'patcher'  best_iter=200  best_thr=0.30  val_F1=0.879

[43/63] Label 43: 'porn'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.993886
[100]	valid's auc: 0.995714
Early stopping, best iteration is:
[124]	valid's auc: 0.995806
[043] 'porn'  best_iter=124  best_thr=0.35  val_F1=0.969

[44/63] Label 44: 'proxy'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.968857
[100]	valid's auc: 0.981193
[150]	valid's auc: 0.985702
[200]	valid's auc: 0.988367
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.988367
[044] 'proxy'  best_iter=200  best_thr=0.40  val_F1=0.918

[45/63] Label 45: 'pua'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.964961
[100]	valid's auc: 0.969287
[150]	valid's auc: 0.971223
[200]	valid's auc: 0.972508
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.972508
[045] 'pua'  best_iter=200  best_thr=0.40  val_F1=0.854

[46/63] Label 46: 'rahack'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.983612
[100]	valid's auc: 0.984068
Early stopping, best iteration is:
[123]	valid's auc: 0.984135
[046] 'rahack'  best_iter=123  best_thr=0.55  val_F1=0.912

[47/63] Label 47: 'ransom'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.96715
[100]	valid's auc: 0.978842
[150]	valid's auc: 0.984114
[200]	valid's auc: 0.9871
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.9871
[047] 'ransom'  best_iter=200  best_thr=0.40  val_F1=0.918

[48/63] Label 48: 'rat'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.986859
[100]	valid's auc: 0.991396
[150]	valid's auc: 0.993012
[200]	valid's auc: 0.993904
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.993904
[048] 'rat'  best_iter=200  best_thr=0.40  val_F1=0.944

[49/63] Label 49: 'riskware'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.969922
[100]	valid's auc: 0.97933
[150]	valid's auc: 0.983421
[200]	valid's auc: 0.985476
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.985476
[049] 'riskware'  best_iter=200  best_thr=0.30  val_F1=0.896

[50/63] Label 50: 'rootkit'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.990816
[100]	valid's auc: 0.994827
[150]	valid's auc: 0.996166
[200]	valid's auc: 0.996883
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.996883
[050] 'rootkit'  best_iter=200  best_thr=0.35  val_F1=0.975

[51/63] Label 51: 'screensaver'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.998758
[100]	valid's auc: 0.999089
[150]	valid's auc: 0.999114
[200]	valid's auc: 0.999115
Did not meet early stopping. Best iteration is:
[192]	valid's auc: 0.999119
[051] 'screensaver'  best_iter=192  best_thr=0.60  val_F1=0.984

[52/63] Label 52: 'selfdel'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.998368
[100]	valid's auc: 0.99901
Early stopping, best iteration is:
[115]	valid's auc: 0.999106
[052] 'selfdel'  best_iter=115  best_thr=0.40  val_F1=0.990

[53/63] Label 53: 'servstart'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.995608
[100]	valid's auc: 0.998217
[150]	valid's auc: 0.998499
Early stopping, best iteration is:
[137]	valid's auc: 0.998588
[053] 'servstart'  best_iter=137  best_thr=0.30  val_F1=0.986

[54/63] Label 54: 'spam'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.981441
[100]	valid's auc: 0.987882
[150]	valid's auc: 0.991166
[200]	valid's auc: 0.991772
Did not meet early stopping. Best iteration is:
[194]	valid's auc: 0.991971
[054] 'spam'  best_iter=194  best_thr=0.35  val_F1=0.953

[55/63] Label 55: 'spyware'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.914263
[100]	valid's auc: 0.934022
[150]	valid's auc: 0.944599
[200]	valid's auc: 0.951093
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.951093
[055] 'spyware'  best_iter=200  best_thr=0.35  val_F1=0.803

[56/63] Label 56: 'startpage'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.985291
[100]	valid's auc: 0.991893
[150]	valid's auc: 0.994096
[200]	valid's auc: 0.995166
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.995166
[056] 'startpage'  best_iter=200  best_thr=0.35  val_F1=0.955

[57/63] Label 57: 'stealer'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.981673
Early stopping, best iteration is:
[78]	valid's auc: 0.984056
[057] 'stealer'  best_iter=78  best_thr=0.55  val_F1=0.947

[58/63] Label 58: 'toolbar'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.996953
Early stopping, best iteration is:
[68]	valid's auc: 0.997317
[058] 'toolbar'  best_iter=68  best_thr=0.35  val_F1=0.971

[59/63] Label 59: 'vbinject'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.996593
[100]	valid's auc: 0.997744
[150]	valid's auc: 0.998179
[200]	valid's auc: 0.998351
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.998351
[059] 'vbinject'  best_iter=200  best_thr=0.40  val_F1=0.974

[60/63] Label 60: 'virtool'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.940863
[100]	valid's auc: 0.955325
[150]	valid's auc: 0.960141
[200]	valid's auc: 0.962179
Did not meet early stopping. Best iteration is:
[194]	valid's auc: 0.962559
[060] 'virtool'  best_iter=194  best_thr=0.35  val_F1=0.827

[61/63] Label 61: 'virus'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.959146
[100]	valid's auc: 0.971735
[150]	valid's auc: 0.978189
[200]	valid's auc: 0.981733
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.981733
[061] 'virus'  best_iter=200  best_thr=0.40  val_F1=0.887

[62/63] Label 62: 'webtoolbar'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.99888
[100]	valid's auc: 0.99938

,experiment,groups,n_features,label_idx,label_name,best_threshold,val_F1,time_min
0,all_except_header_sections,"byte_hist,byte_entropy,general,strings,imports...",2064,0,adware,0.45,0.912250,0.611323
1,all_except_header_sections,"byte_hist,byte_entropy,general,strings,imports...",2064,1,antiav,0.35,0.939370,0.588880
2,all_except_header_sections,"byte_hist,byte_entropy,general,strings,imports...",2064,2,antifw,0.30,0.996221,0.409259
3,all_except_header_sections,"byte_hist,byte_entropy,general,strings,imports...",2064,3,autorun,0.40,0.922543,0.605301
4,all_except_header_sections,"byte_hist,byte_entropy,general,strings,imports...",2064,4,backdoor,0.35,0.764314,0.593944

**Cell 20: Metrics for VAL set EXP 2**

In [35]:
# VAL metrics για το Experiment 2 (all_except_header_sections)

metrics_exp2_val = overall_metrics_from_df(df_exp2, feature_cols_exp2)
metrics_exp2_val

            Micro   Macro  Weighted
Precision  0.9062  0.9225    0.9083
Recall     0.9249  0.9436    0.9249
F1-score   0.9155  0.9322    0.9158
AUC        0.9882  0.9895    0.9850

**Cell 21: Metrics for TEST set EXP 2**

In [36]:
# TEST metrics για το Experiment 2 (all_except_header_sections)

test_metrics_exp2 = overall_test_metrics_for_experiment(
    df_exp2,
    feature_cols_exp2,
    exp2_name,        # "all_except_header_sections"
)
test_metrics_exp2

[test:all_except_header_sections] part 1/45 ...
[test:all_except_header_sections] part 2/45 ...
[test:all_except_header_sections] part 3/45 ...
[test:all_except_header_sections] part 4/45 ...
[test:all_except_header_sections] part 5/45 ...
[test:all_except_header_sections] part 6/45 ...
[test:all_except_header_sections] part 7/45 ...
[test:all_except_header_sections] part 8/45 ...
[test:all_except_header_sections] part 9/45 ...
[test:all_except_header_sections] part 10/45 ...
[test:all_except_header_sections] part 11/45 ...
[test:all_except_header_sections] part 12/45 ...
[test:all_except_header_sections] part 13/45 ...
[test:all_except_header_sections] part 14/45 ...
[test:all_except_header_sections] part 15/45 ...
[test:all_except_header_sections] part 16/45 ...
[test:all_except_header_sections] part 17/45 ...
[test:all_except_header_sections] part 18/45 ...
[test:all_except_header_sections] part 19/45 ...
[test:all_except_header_sections] part 20/45 ...
[test:all_except_header_sections] part 21/45 ...
[test:all_except_header_sections] part 22/45 ...
[test:all_except_header_sections] part 23/45 ...
[test:all_except_header_sections] part 24/45 ...
[test:all_except_header_sections] part 25/45 ...
[test:all_except_header_sections] part 26/45 ...
[test:all_except_header_sections] part 27/45 ...
[test:all_except_header_sections] part 28/45 ...
[test:all_except_header_sections] part 29/45 ...
[test:all_except_header_sections] part 30/45 ...
[test:all_except_header_sections] part 31/45 ...
[test:all_except_header_sections] part 32/45 ...
[test:all_except_header_sections] part 33/45 ...
[test:all_except_header_sections] part 34/45 ...
[test:all_except_header_sections] part 35/45 ...
[test:all_except_header_sections] part 36/45 ...
[test:all_except_header_sections] part 37/45 ...
[test:all_except_header_sections] part 38/45 ...
[test:all_except_header_sections] part 39/45 ...
[test:all_except_header_sections] part 40/45 ...
[test:all_except_header_sections] part 41/45 ...
[test:all_except_header_sections] part 42/45 ...
[test:all_except_header_sections] part 43/45 ...
[test:all_except_header_sections] part 44/45 ...
[test:all_except_header_sections] part 45/45 ...

/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(

Saved TEST metrics -> /Users/georgektenas/Desktop/Malware Project/data/behavior_vectors_paper/results_ablation/overall_test_metrics_all_except_header_sections.csv

/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(

            Micro   Macro  Weighted
Precision  0.1351  0.1115    0.4614
Recall     0.2859  0.2478    0.2859
F1-score   0.1835  0.1121    0.2752
AUC        0.8443     NaN    0.7461

**Cell 22: Training for EXPERIMENT 3**

In [37]:
# κρατάμε όλα εκτός από byte_hist & byte_entropy
# groups: header, sections, general, strings, imports, exports, data_dirs

exp3_name = "all_except_bytehist_entropy"
exp3_groups = [
    "header",
    "sections",
    "general",
    "strings",
    "imports",
    "exports",
    "data_dirs",
]

# Ποιες στήλες features αντιστοιχούν σε αυτά τα groups
feature_cols_exp3 = cols_for_groups(exp3_groups)

# Τρέχουμε LightGBM για ΟΛΑ τα labels, όπως στα προηγούμενα πειράματα
df_exp3 = run_experiment_all_labels(exp3_name, exp3_groups)
df_exp3.head()

################################################################################
Running experiment 'all_except_bytehist_entropy'
  1869 features from groups ['header', 'sections', 'general', 'strings', 'imports', 'exports', 'data_dirs']

[00/63] Label 0: 'adware'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.97985
[100]	valid's auc: 0.985526
[150]	valid's auc: 0.987968
[200]	valid's auc: 0.989282
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.989282
[000] 'adware'  best_iter=200  best_thr=0.45  val_F1=0.912

[01/63] Label 1: 'antiav'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.979715
[100]	valid's auc: 0.986518
[150]	valid's auc: 0.989962
[200]	valid's auc: 0.991709
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.991709
[001] 'antiav'  best_iter=200  best_thr=0.40  val_F1=0.945

[02/63] Label 2: 'antifw'
Training until validation scores don't improve for 20 rounds
Early stopping, best iteration is:
[29]	valid's auc: 0.999729
[002] 'antifw'  best_iter=29  best_thr=0.45  val_F1=0.996

[03/63] Label 3: 'autorun'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.980438
[100]	valid's auc: 0.986717
[150]	valid's auc: 0.989413
[200]	valid's auc: 0.991041
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.991041
[003] 'autorun'  best_iter=200  best_thr=0.40  val_F1=0.928

[04/63] Label 4: 'backdoor'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.906545
[100]	valid's auc: 0.926493
[150]	valid's auc: 0.937
[200]	valid's auc: 0.943453
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.943453
[004] 'backdoor'  best_iter=200  best_thr=0.35  val_F1=0.776

[05/63] Label 5: 'banker'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.973097
[100]	valid's auc: 0.982423
[150]	valid's auc: 0.986528
[200]	valid's auc: 0.988727
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.988727
[005] 'banker'  best_iter=200  best_thr=0.40  val_F1=0.928

[06/63] Label 6: 'bho'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.988282
[100]	valid's auc: 0.994072
[150]	valid's auc: 0.995992
[200]	valid's auc: 0.996834
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.996834
[006] 'bho'  best_iter=200  best_thr=0.40  val_F1=0.961

[07/63] Label 7: 'binder'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.989071
[100]	valid's auc: 0.992099
[150]	valid's auc: 0.993415
[200]	valid's auc: 0.994004
Did not meet early stopping. Best iteration is:
[199]	valid's auc: 0.994012
[007] 'binder'  best_iter=199  best_thr=0.55  val_F1=0.950

[08/63] Label 8: 'blocker'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.958484
[100]	valid's auc: 0.968774
[150]	valid's auc: 0.97377
[200]	valid's auc: 0.976261
Did not meet early stopping. Best iteration is:
[199]	valid's auc: 0.976273
[008] 'blocker'  best_iter=199  best_thr=0.40  val_F1=0.880

[09/63] Label 9: 'bundler'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.972501
[100]	valid's auc: 0.975027
[150]	valid's auc: 0.97593
[200]	valid's auc: 0.976249
Did not meet early stopping. Best iteration is:
[186]	valid's auc: 0.976347
[009] 'bundler'  best_iter=186  best_thr=0.35  val_F1=0.842

[10/63] Label 10: 'clicker'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.96046
[100]	valid's auc: 0.9729
[150]	valid's auc: 0.979276
[200]	valid's auc: 0.982496
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.982496
[010] 'clicker'  best_iter=200  best_thr=0.45  val_F1=0.900

[11/63] Label 11: 'coinminer'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.989666
[100]	valid's auc: 0.993042
[150]	valid's auc: 0.994177
[200]	valid's auc: 0.99485
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.99485
[011] 'coinminer'  best_iter=200  best_thr=0.45  val_F1=0.956

[12/63] Label 12: 'constructor'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.975409
[100]	valid's auc: 0.983379
[150]	valid's auc: 0.985779
[200]	valid's auc: 0.987057
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.987057
[012] 'constructor'  best_iter=200  best_thr=0.50  val_F1=0.914

[13/63] Label 13: 'cryptor'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.965425
[100]	valid's auc: 0.976666
[150]	valid's auc: 0.981444
[200]	valid's auc: 0.984072
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.984072
[013] 'cryptor'  best_iter=200  best_thr=0.40  val_F1=0.910

[14/63] Label 14: 'ddos'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.974761
[100]	valid's auc: 0.980017
[150]	valid's auc: 0.981533
Early stopping, best iteration is:
[147]	valid's auc: 0.981691
[014] 'ddos'  best_iter=147  best_thr=0.40  val_F1=0.927

[15/63] Label 15: 'dialer'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.995915
[100]	valid's auc: 0.997657
[150]	valid's auc: 0.998474
[200]	valid's auc: 0.998938
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.998938
[015] 'dialer'  best_iter=200  best_thr=0.35  val_F1=0.983

[16/63] Label 16: 'downloader'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.914565
[100]	valid's auc: 0.933314
[150]	valid's auc: 0.942368
[200]	valid's auc: 0.94818
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.94818
[016] 'downloader'  best_iter=200  best_thr=0.40  val_F1=0.799

[17/63] Label 17: 'dropper'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.933145
[100]	valid's auc: 0.945073
[150]	valid's auc: 0.952286
[200]	valid's auc: 0.956732
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.956732
[017] 'dropper'  best_iter=200  best_thr=0.40  val_F1=0.813

[18/63] Label 18: 'email'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.998755
[100]	valid's auc: 0.999336
[150]	valid's auc: 0.999458
[200]	valid's auc: 0.999515
Did not meet early stopping. Best iteration is:
[197]	valid's auc: 0.999516
[018] 'email'  best_iter=197  best_thr=0.45  val_F1=0.992

[19/63] Label 19: 'exploit'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.962842
[100]	valid's auc: 0.968355
[150]	valid's auc: 0.969876
[200]	valid's auc: 0.971426
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.971426
[019] 'exploit'  best_iter=200  best_thr=0.40  val_F1=0.866

[20/63] Label 20: 'fakealert'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.97451
[100]	valid's auc: 0.982231
[150]	valid's auc: 0.985861
[200]	valid's auc: 0.987817
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.987817
[020] 'fakealert'  best_iter=200  best_thr=0.45  val_F1=0.914

[21/63] Label 21: 'fakeantivirus'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.984997
[100]	valid's auc: 0.990113
[150]	valid's auc: 0.992555
[200]	valid's auc: 0.99379
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.99379
[021] 'fakeantivirus'  best_iter=200  best_thr=0.40  val_F1=0.942

[22/63] Label 22: 'flooder'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.997464
[100]	valid's auc: 0.998326
[150]	valid's auc: 0.998628
[200]	valid's auc: 0.99892
Did not meet early stopping. Best iteration is:
[196]	valid's auc: 0.998926
[022] 'flooder'  best_iter=196  best_thr=0.30  val_F1=0.981

[23/63] Label 23: 'fraud'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.970901
[100]	valid's auc: 0.982973
[150]	valid's auc: 0.987842
[200]	valid's auc: 0.990269
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.990269
[023] 'fraud'  best_iter=200  best_thr=0.40  val_F1=0.928

[24/63] Label 24: 'ftp'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.989819
[100]	valid's auc: 0.993151
Early stopping, best iteration is:
[107]	valid's auc: 0.993428
[024] 'ftp'  best_iter=107  best_thr=0.35  val_F1=0.932

[25/63] Label 25: 'gamehack'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.998031
[100]	valid's auc: 0.999134
Early stopping, best iteration is:
[117]	valid's auc: 0.99927
[025] 'gamehack'  best_iter=117  best_thr=0.15  val_F1=0.984

[26/63] Label 26: 'gamethief'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.981735
[100]	valid's auc: 0.987881
[150]	valid's auc: 0.9899
[200]	valid's auc: 0.990937
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.990937
[026] 'gamethief'  best_iter=200  best_thr=0.35  val_F1=0.932

[27/63] Label 27: 'hacktool'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.965442
[100]	valid's auc: 0.976756
[150]	valid's auc: 0.981216
[200]	valid's auc: 0.983627
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.983627
[027] 'hacktool'  best_iter=200  best_thr=0.40  val_F1=0.895

[28/63] Label 28: 'hoax'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.99077
[100]	valid's auc: 0.996848
[150]	valid's auc: 0.998184
[200]	valid's auc: 0.998622
Did not meet early stopping. Best iteration is:
[199]	valid's auc: 0.998622
[028] 'hoax'  best_iter=199  best_thr=0.40  val_F1=0.983

[29/63] Label 29: 'hotbar'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.999657
[100]	valid's auc: 0.999709
Early stopping, best iteration is:
[95]	valid's auc: 0.999711
[029] 'hotbar'  best_iter=95  best_thr=0.50  val_F1=0.990

[30/63] Label 30: 'injector'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.95597
[100]	valid's auc: 0.968284
[150]	valid's auc: 0.974077
[200]	valid's auc: 0.977418
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.977418
[030] 'injector'  best_iter=200  best_thr=0.40  val_F1=0.874

[31/63] Label 31: 'installer'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.999698
Early stopping, best iteration is:
[76]	valid's auc: 0.999838
[031] 'installer'  best_iter=76  best_thr=0.20  val_F1=0.996

[32/63] Label 32: 'ircbot'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.964603
[100]	valid's auc: 0.976291
[150]	valid's auc: 0.982078
[200]	valid's auc: 0.985184
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.985184
[032] 'ircbot'  best_iter=200  best_thr=0.35  val_F1=0.901

[33/63] Label 33: 'joke'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.988132
[100]	valid's auc: 0.993234
[150]	valid's auc: 0.994292
Early stopping, best iteration is:
[155]	valid's auc: 0.994431
[033] 'joke'  best_iter=155  best_thr=0.45  val_F1=0.948

[34/63] Label 34: 'keygen'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.993725
[100]	valid's auc: 0.995874
[150]	valid's auc: 0.996431
Early stopping, best iteration is:
[133]	valid's auc: 0.996511
[034] 'keygen'  best_iter=133  best_thr=0.65  val_F1=0.956

[35/63] Label 35: 'keylogger'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.970554
[100]	valid's auc: 0.981958
[150]	valid's auc: 0.986595
[200]	valid's auc: 0.989009
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.989009
[035] 'keylogger'  best_iter=200  best_thr=0.40  val_F1=0.918

[36/63] Label 36: 'lockscreen'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.981952
[100]	valid's auc: 0.987003
[150]	valid's auc: 0.988735
[200]	valid's auc: 0.9895
Did not meet early stopping. Best iteration is:
[198]	valid's auc: 0.989516
[036] 'lockscreen'  best_iter=198  best_thr=0.55  val_F1=0.930

[37/63] Label 37: 'net'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.985323
[100]	valid's auc: 0.986509
[150]	valid's auc: 0.986893
Early stopping, best iteration is:
[143]	valid's auc: 0.986929
[037] 'net'  best_iter=143  best_thr=0.45  val_F1=0.908

[38/63] Label 38: 'nettool'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.990318
Early stopping, best iteration is:
[76]	valid's auc: 0.991575
[038] 'nettool'  best_iter=76  best_thr=0.65  val_F1=0.950

[39/63] Label 39: 'nuker'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.991923
[100]	valid's auc: 0.997981
[150]	valid's auc: 0.998683
[200]	valid's auc: 0.998815
Did not meet early stopping. Best iteration is:
[189]	valid's auc: 0.998859
[039] 'nuker'  best_iter=189  best_thr=0.25  val_F1=0.957

[40/63] Label 40: 'packed'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.94613
[100]	valid's auc: 0.958259
[150]	valid's auc: 0.964409
[200]	valid's auc: 0.967842
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.967842
[040] 'packed'  best_iter=200  best_thr=0.40  val_F1=0.843

[41/63] Label 41: 'passwordstealer'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.946386
[100]	valid's auc: 0.961017
[150]	valid's auc: 0.968275
[200]	valid's auc: 0.971939
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.971939
[041] 'passwordstealer'  best_iter=200  best_thr=0.40  val_F1=0.869

[42/63] Label 42: 'patcher'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.968703
[100]	valid's auc: 0.979161
[150]	valid's auc: 0.983488
[200]	valid's auc: 0.985265
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.985265
[042] 'patcher'  best_iter=200  best_thr=0.40  val_F1=0.901

[43/63] Label 43: 'porn'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.994128
[100]	valid's auc: 0.996486
[150]	valid's auc: 0.996703
Early stopping, best iteration is:
[135]	valid's auc: 0.996779
[043] 'porn'  best_iter=135  best_thr=0.30  val_F1=0.973

[44/63] Label 44: 'proxy'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.973008
[100]	valid's auc: 0.983358
[150]	valid's auc: 0.987662
[200]	valid's auc: 0.989764
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.989764
[044] 'proxy'  best_iter=200  best_thr=0.40  val_F1=0.927

[45/63] Label 45: 'pua'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.964635
[100]	valid's auc: 0.969016
[150]	valid's auc: 0.971043
[200]	valid's auc: 0.97229
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.97229
[045] 'pua'  best_iter=200  best_thr=0.40  val_F1=0.855

[46/63] Label 46: 'rahack'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.985131
Early stopping, best iteration is:
[72]	valid's auc: 0.985401
[046] 'rahack'  best_iter=72  best_thr=0.55  val_F1=0.913

[47/63] Label 47: 'ransom'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.975917
[100]	valid's auc: 0.984499
[150]	valid's auc: 0.988216
[200]	valid's auc: 0.990231
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.990231
[047] 'ransom'  best_iter=200  best_thr=0.45  val_F1=0.931

[48/63] Label 48: 'rat'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.989364
[100]	valid's auc: 0.994305
[150]	valid's auc: 0.995262
[200]	valid's auc: 0.995807
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.995807
[048] 'rat'  best_iter=200  best_thr=0.45  val_F1=0.952

[49/63] Label 49: 'riskware'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.971687
[100]	valid's auc: 0.981088
[150]	valid's auc: 0.98513
[200]	valid's auc: 0.987106
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.987106
[049] 'riskware'  best_iter=200  best_thr=0.40  val_F1=0.901

[50/63] Label 50: 'rootkit'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.991527
[100]	valid's auc: 0.995645
[150]	valid's auc: 0.996827
[200]	valid's auc: 0.997196
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.997196
[050] 'rootkit'  best_iter=200  best_thr=0.35  val_F1=0.976

[51/63] Label 51: 'screensaver'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.998702
[100]	valid's auc: 0.998984
Early stopping, best iteration is:
[121]	valid's auc: 0.998993
[051] 'screensaver'  best_iter=121  best_thr=0.55  val_F1=0.981

[52/63] Label 52: 'selfdel'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.999237
[100]	valid's auc: 0.999607
Early stopping, best iteration is:
[91]	valid's auc: 0.999643
[052] 'selfdel'  best_iter=91  best_thr=0.30  val_F1=0.993

[53/63] Label 53: 'servstart'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.998653
[100]	valid's auc: 0.999388
[150]	valid's auc: 0.999568
[200]	valid's auc: 0.999641
Did not meet early stopping. Best iteration is:
[186]	valid's auc: 0.999652
[053] 'servstart'  best_iter=186  best_thr=0.15  val_F1=0.988

[54/63] Label 54: 'spam'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.985353
[100]	valid's auc: 0.990103
[150]	valid's auc: 0.993016
Early stopping, best iteration is:
[154]	valid's auc: 0.993364
[054] 'spam'  best_iter=154  best_thr=0.20  val_F1=0.953

[55/63] Label 55: 'spyware'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.917994
[100]	valid's auc: 0.93849
[150]	valid's auc: 0.948922
[200]	valid's auc: 0.955119
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.955119
[055] 'spyware'  best_iter=200  best_thr=0.40  val_F1=0.808

[56/63] Label 56: 'startpage'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.986046
[100]	valid's auc: 0.992287
[150]	valid's auc: 0.994516
[200]	valid's auc: 0.995699
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.995699
[056] 'startpage'  best_iter=200  best_thr=0.45  val_F1=0.958

[57/63] Label 57: 'stealer'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.979799
[100]	valid's auc: 0.986071
[150]	valid's auc: 0.987396
Early stopping, best iteration is:
[175]	valid's auc: 0.988055
[057] 'stealer'  best_iter=175  best_thr=0.50  val_F1=0.958

[58/63] Label 58: 'toolbar'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.996795
[100]	valid's auc: 0.996948
Early stopping, best iteration is:
[84]	valid's auc: 0.997253
[058] 'toolbar'  best_iter=84  best_thr=0.35  val_F1=0.975

[59/63] Label 59: 'vbinject'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.997226
[100]	valid's auc: 0.998192
[150]	valid's auc: 0.998489
[200]	valid's auc: 0.998594
Did not meet early stopping. Best iteration is:
[199]	valid's auc: 0.998595
[059] 'vbinject'  best_iter=199  best_thr=0.35  val_F1=0.976

[60/63] Label 60: 'virtool'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.94442
[100]	valid's auc: 0.956145
[150]	valid's auc: 0.962269
[200]	valid's auc: 0.964916
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.964916
[060] 'virtool'  best_iter=200  best_thr=0.45  val_F1=0.853

[61/63] Label 61: 'virus'
Training until validation scores don't improve for 20 rounds
[50]	valid's auc: 0.977967
[100]	valid's auc: 0.985628
[150]	valid's auc: 0.988934
[200]	valid's auc: 0.990659
Did not meet early stopping. Best iteration is:
[200]	valid's auc: 0.990659
[061] 'virus'  best_iter=200  best_thr=0.40  val_F1=0.921

[62/63] Label 62: 'webtoolbar'

,experiment,groups,n_features,label_idx,label_name,best_threshold,val_F1,time_min
0,all_except_bytehist_entropy,"header,sections,general,strings,imports,export...",1869,0,adware,0.45,0.911600,0.559333
1,all_except_bytehist_entropy,"header,sections,general,strings,imports,export...",1869,1,antiav,0.40,0.944695,0.545680
2,all_except_bytehist_entropy,"header,sections,general,strings,imports,export...",1869,2,antifw,0.45,0.996221,0.455234
3,all_except_bytehist_entropy,"header,sections,general,strings,imports,export...",1869,3,autorun,0.40,0.927748,0.558176
4,all_except_bytehist_entropy,"header,sections,general,strings,imports,export...",1869,4,backdoor,0.35,0.776105,0.544342

**Cell 23: Metrics for VAL set EXP 3**

In [ ]:
# VAL metrics για το Experiment 3

metrics_exp3_val = overall_metrics_from_df(df_exp3, feature_cols_exp3)
metrics_exp3_val

            Micro   Macro  Weighted
Precision  0.9128  0.9270    0.9146
Recall     0.9277  0.9467    0.9277
F1-score   0.9202  0.9361    0.9203
AUC        0.9907  0.9905    0.9864

**Cell 24: Metrics for TEST set EXP 3**

In [39]:
# TEST metrics για το Experiment 3 

test_metrics_exp3 = overall_test_metrics_for_experiment(
    df_exp3,
    feature_cols_exp3,
    exp3_name,
)
test_metrics_exp3

[test:all_except_bytehist_entropy] part 1/45 ...
[test:all_except_bytehist_entropy] part 2/45 ...
[test:all_except_bytehist_entropy] part 3/45 ...
[test:all_except_bytehist_entropy] part 4/45 ...
[test:all_except_bytehist_entropy] part 5/45 ...
[test:all_except_bytehist_entropy] part 6/45 ...
[test:all_except_bytehist_entropy] part 7/45 ...
[test:all_except_bytehist_entropy] part 8/45 ...
[test:all_except_bytehist_entropy] part 9/45 ...
[test:all_except_bytehist_entropy] part 10/45 ...
[test:all_except_bytehist_entropy] part 11/45 ...
[test:all_except_bytehist_entropy] part 12/45 ...
[test:all_except_bytehist_entropy] part 13/45 ...
[test:all_except_bytehist_entropy] part 14/45 ...
[test:all_except_bytehist_entropy] part 15/45 ...
[test:all_except_bytehist_entropy] part 16/45 ...
[test:all_except_bytehist_entropy] part 17/45 ...
[test:all_except_bytehist_entropy] part 18/45 ...
[test:all_except_bytehist_entropy] part 19/45 ...
[test:all_except_bytehist_entropy] part 20/45 ...
[test:all_except_bytehist_entropy] part 21/45 ...
[test:all_except_bytehist_entropy] part 22/45 ...
[test:all_except_bytehist_entropy] part 23/45 ...
[test:all_except_bytehist_entropy] part 24/45 ...
[test:all_except_bytehist_entropy] part 25/45 ...
[test:all_except_bytehist_entropy] part 26/45 ...
[test:all_except_bytehist_entropy] part 27/45 ...
[test:all_except_bytehist_entropy] part 28/45 ...
[test:all_except_bytehist_entropy] part 29/45 ...
[test:all_except_bytehist_entropy] part 30/45 ...
[test:all_except_bytehist_entropy] part 31/45 ...
[test:all_except_bytehist_entropy] part 32/45 ...
[test:all_except_bytehist_entropy] part 33/45 ...
[test:all_except_bytehist_entropy] part 34/45 ...
[test:all_except_bytehist_entropy] part 35/45 ...
[test:all_except_bytehist_entropy] part 36/45 ...
[test:all_except_bytehist_entropy] part 37/45 ...
[test:all_except_bytehist_entropy] part 38/45 ...
[test:all_except_bytehist_entropy] part 39/45 ...
[test:all_except_bytehist_entropy] part 40/45 ...
[test:all_except_bytehist_entropy] part 41/45 ...
[test:all_except_bytehist_entropy] part 42/45 ...
[test:all_except_bytehist_entropy] part 43/45 ...
[test:all_except_bytehist_entropy] part 44/45 ...
[test:all_except_bytehist_entropy] part 45/45 ...

/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(

Saved TEST metrics -> /Users/georgektenas/Desktop/Malware Project/data/behavior_vectors_paper/results_ablation/overall_test_metrics_all_except_bytehist_entropy.csv

/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/envs/maltrain/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(

            Micro   Macro  Weighted
Precision  0.0812  0.1432    0.5364
Recall     0.2673  0.2807    0.2673
F1-score   0.1246  0.1312    0.2755
AUC        0.8512     NaN    0.8218